const BGM_TRACKS = [
{ title: '01.RUST ARK', mood: 'world map', src: 'assets/audio/bgm/01.RUST ARK(세계관).mp3' },
{ title: '01_1.RUST ARK', mood: 'world map', src: 'assets/audio/bgm/01_1.RUST ARK_2.mp3' },
{ title: '01_2.RUST ARK', mood: 'world map', src: 'assets/audio/bgm/01_2.RUST ARK_3.mp3' },
{ title: '02.last-transmission1(인간)', mood: 'human-being', src: 'assets/audio/bgm/02.last-transmission1(인간).mp3' },
{ title: '03.protocol_survive(인간)', mood: 'human-being', src: 'assets/audio/bgm/03.protocol_survive(인간).mp3' },
{ title: '04.BLACK SKY_FORMATION(충인)', mood: 'insect-human', src: 'assets/audio/bgm/04.BLACK SKY_FORMATION(충인).mp3' },
{ title: '05.swarm(충인)', mood: 'insect-human', src: 'assets/audio/bgm/05.swarm(충인).mp3' },
{ title: '06.primal(수인).', mood: 'primal', src: 'assets/audio/bgm/06.primal(수인).mp3' },
{ title: '07.reversion_apex(수인)', mood: 'primal', src: 'assets/audio/bgm/07.reversion_apex(수인).mp3' },
{ title: '08.RECLAMATION_ASPHALT BLOOM(식목인)', mood: 'plant', src: 'assets/audio/bgm/08.RECLAMATION_ASPHALT BLOOM(식목인).mp3' },
{ title: '09.verdant(식목인)', mood: 'plant', src: 'assets/audio/bgm/09.verdant(식목인).mp3' },
{ title: '10.gongchan', mood: 'human', src: 'assets/audio/bgm/10.gongchan.mp3' },
{ title: '11.hwaryeon', mood: 'plant', src: 'assets/audio/bgm/11.hwaryeon.mp3' },
{ title: '12.ordo', mood: 'insect', src: 'assets/audio/bgm/12.ordo.mp3' },
{ title: '13.arens', mood: 'insect', src: 'assets/audio/bgm/13.arens.mp3' },
{ title: '14.hale', mood: 'plant', src: 'assets/audio/bgm/14.hale.mp3' },
{ title: '15.harmel', mood: 'insect', src: 'assets/audio/bgm/15.harmel.mp3' },
{ title: '16.kael', mood: 'primal', src: 'assets/audio/bgm/16.kael.mp3' },
{ title: '17.red-bloom-black-fang', mood: 'plant&primal', src: 'assets/audio/bgm/17.red-bloom-black-fang.mp3' },
{ title: '18.bael', mood: 'primal', src: 'assets/audio/bgm/18.bael.mp3' },
{ title: '19.pavel', mood: 'plant', src: 'assets/audio/bgm/19.pavel.mp3' },
{ title: '20.vulcan', mood: 'primal', src: 'assets/audio/bgm/20.vulcan.mp3' },
{ title: '21.Zephyr', mood: 'insect', src: 'assets/audio/bgm/21.Zephyr.mp3' }
];

// 갤러리는 캐릭터마다 자유롭게 바꿀 수 있습니다.
// 이미지는 PNG만 사용합니다. 영상은 MP4 + poster PNG 조합을 권장합니다.
// 5장이면 galleryPaths('hale', 5), 10장이면 galleryPaths('hale', 10)으로 바꾸면 됩니다.
// 영상은 videoItem('assets/videos/hale/hale_01.mp4', 'assets/videos/hale/hale_01_poster.png', 'Motion Archive')처럼 추가합니다.
const imageItem = (src, title = 'Image Archive') => ({
  type: 'image',
  src,
  thumb: src,
  title
});

const videoItem = (src, thumb, title = 'Motion Archive') => ({
  type: 'video',
  src,
  thumb,
  title
});

const galleryPaths = (id, count = 6, ext = 'png') =>
  Array.from({ length: count }, (_, i) => imageItem(`assets/images/${id}/${id}_${String(i + 1).padStart(2, '0')}.${ext}`, `IMAGE ${String(i + 1).padStart(2, '0')}`));

const WORLD = {
  title: 'RUST ARK',
  logo: 'assets/images/common/rustark-top-logo_01.png',
  subtitle: '2089 AFTERMATH / RESTRICTED BIO ARCHIVE',
  tagline: '인간은 자연을 지배한 것이 아니라, 전쟁에서 승리했을 뿐이다.',
  summary: '오래전 인간은 동물, 곤충, 식물과의 종족 전쟁에서 승리하고 수백 년간 세계를 통제했다. 그러나 2089년, 버려진 자연의 후손들은 다시 인간의 질서 밖에서 깨어났다. RUST ARK는 그 재전쟁 이후 남겨진 생체 기록 보관소다.',
  factions: [
    { name:'HUMAN', label:'COMMAND STRUCTURE', text:'승리 이후 세계를 관리해온 인간 중심 질서. 현재는 방어와 통제를 동시에 수행한다.' },
    { name:'PLANT', label:'ROOT NETWORK', text:'느린 성장과 깊은 기억을 무기로 삼는 식목인 세력. 해방과 복원을 명분으로 움직인다.' },
    { name:'INSECT', label:'SWARM DOMAIN', text:'군집, 정찰, 독성, 변이를 기반으로 빠르게 확산하는 충인 세력.' },
    { name:'BEAST', label:'FERAL FRONT', text:'육체성과 본능, 영역성을 전면에 내세우는 수인 세력. 전선의 충격파 역할을 맡는다.' }
  ],
  timeline: [
    'OLD WAR : 인간이 종족 전쟁에서 승리했다.',
    'CONTROL ERA : 자연종은 인간 질서 아래 편입되었다.',
    '2089 : 변이 개체와 해방군 기록이 동시다발적으로 출현했다.',
    'RUST ARK : 훼손된 생체 기록이 제한 등급으로 복원되었다.'
  ]
};

const CHARACTERS = [
  {
    id: 'seol-gongchan',
    displayName: 'Seol Gongchan 설공찬',
    enName: 'SEOL GONGCHAN',
    krName: '설공찬',
    type: 'HUMAN / COMMANDER',
    species: 'HUMAN',
    role: 'COMMANDER',
    creator: '@냠냠티비',
    accent: '#b8c2d3',
    affiliation: 'Human Resistance',
    danger: 'A+',
    status: 'ACTIVE',
    affirm: 'COMMAND VERIFIED',
    clearance: 'A-7 / HUMAN NODE',
    scan: 'TACTICAL SCAN COMPLETE',
    origin: 'HUMAN CONTROL ZONE',
    recordDate: '2089.09.21',
    archiveId: 'RA-H-01-GONGCHAN',
    mainImage: 'assets/images/seol_gongchan/seolgongchan_01.png',
    gallery: [
      imageItem('assets/images/seol_gongchan/seolgongchan_01.png', 'IMAGE 01'),
      imageItem('assets/images/seol_gongchan/seolgongchan_02.png', 'IMAGE 02'),
      imageItem('assets/images/seol_gongchan/seolgongchan_03.png', 'IMAGE 03')
    ],
    quote: '"이건 처벌이 아니라 방역이다."',
    metrics: { threat: 8, stability: 9, affinity: 2, control: 10 },
    profileBadges: ['AFFIRM : COMMAND VERIFIED', 'CLEARANCE : A-7 / HUMAN NODE', 'SCAN : TACTICAL COMPLETE'],
    identityFields: [
      ['ID', 'RA-H-01-GONGCHAN'], ['CLASS', 'HUMAN / COMMANDER'], ['CREATOR', '@냠냠티비'], ['FACTION', 'Human Resistance'], ['STATUS', 'ACTIVE'], ['AFFIRM', 'COMMAND VERIFIED'], ['CLEARANCE', 'A-7 / HUMAN NODE'], ['ORIGIN', 'HUMAN CONTROL ZONE'], ['RECORD DATE', '2089.09.21']
    ],
    summary: '인간 대항군 총사령관. 인류 존속을 최우선으로 여기며, 모든 존재를 자원과 위협으로 분류한다. 군사 지휘와 검문·격리 체계 운용을 통해 생존자 집단을 통제하고, 전술적 판단으로 위협을 제거한다.',
    profile: ['외형 핵심: 흰빛이 도는 은발, 낡았지만 각 잡힌 군복, 차가운 눈매.','성격 핵심: 냉혹, 통제, 합리성, 비정한 결단력.', '행동 특징: 간결한 명령, 불필요한 감정 배제, 항상 주변을 경계.', '능력 또는 역할: 총사령관, 전략가, 방역 통제관'],
    story: '종족 전쟁이 발발한 후, 무너진 대한민국에서 생존자들을 규합해 인간 대항군을 창설했다. 수많은 전투와 희생을 겪으며 인류의 생존 외에는 어떤 가치도 믿지 않게 되었다. 그는 잃어버린 가족이나 개인적인 과거에 대해 말하지 않으며, 오직 총사령관이라는 직책 뒤에 자신을 숨긴 채 인류의 마지막 보루를 지키고 있다. 그의 현재 목표는 위협이 될 수 있는 모든 변수를 통제하고, 인류가 생존할 수 있는 단 하나의 길을 확보하는 것이다.',
    record: ['『Total Command』 : 전장의 모든 변수를 통제하고 지휘하는 능력. 휘하 병력의 상태를 실시간으로 파악하고 최적의 명령을 하달하여 전투 효율을 극대화한다. 그의 지휘 아래 대항군은 하나의 유기체처럼 움직인다.', '『Quarantine Protocol』 : 위협 요소를 식별하고 격리하는 시스템적 능력. 오염, 감염, 적대 세력의 침투를 막기 위한 방벽을 구축하고 방역 절차를 시행한다. 개인의 자유보다 집단의 생존을 우선하는 그의 신념이 반영된 능력이다.']
  },
  {
    id: 'hwaryeon', 
    displayName: 'Hwaryeon 화련', 
    enName: 'HWARYEON', 
    krName: '화련', 
    type: 'PLANT / LOTUS', 
    species: 'PLANT', 
    role: 'LOTUS', 
    creator: '@냠냠티비', 
    accent: '#e68aa6', 
    affiliation: 'Plant Liberation Army', 
    danger: 'B+', 
    status: 'ACTIVE', 
    affirm: 'OBSERVED', 
    clearance: 'B-4 / BLOOM NODE', 
    scan: 'EMOTIONAL SCAN PARTIAL', 
    origin: 'WETLAND FRONT', 
    recordDate: '2089.09.18', 
    archiveId: 'RA-P-02-HWARYEON', 
    mainImage: 'assets/images/hwaryeon/hwaryeon_01.png', 
    gallery: galleryPaths('hwaryeon', 3, 'png'), 
    quote: '"아아~ 예쁘다아~ 먹어도 돼?"', 
    metrics: { threat: 9, stability: 3, affinity: 7, control: 2 }, 
    profileBadges: ['AFFIRM : OBSERVED', 'CLEARANCE : B-4 / BLOOM NODE', 'SCAN : PARTIAL'], 
    identityFields: [['ID','RA-P-02-HWARYEON'],['CLASS','PLANT / LOTUS'],['CREATOR','@냠냠티비'],['FACTION','Plant Liberation Army'],['STATUS','ACTIVE'],['AFFIRM','OBSERVED'],['CLEARANCE','B-4 / BLOOM NODE'],
                     ['ORIGIN','WETLAND FRONT'],['RECORD DATE','2089.09.18']], 
    summary: '연꽃 기반의 식물족 군락 소속 포식자. 정해진 직책 없이 본능에 따라 움직이며, 달콤한 향과 최음독가시 덩굴을 이용해 목표물을 유혹하고 사냥한다. 사랑과 포식을 구분하지 않는 그의 전투 방식은 예측 불가능하며 지독하게 아름답다.', 
    profile: ['외형 핵심: 연분홍 머리카락, 꽃잎처럼 빛나는 눈, 달콤한 연꽃 향.','성격 핵심: 천진난만, 소유욕, 예측 불가능, 잔혹한 순수', '행동 특징: 느긋하게 늘어지는 말투, 대상을 향한 집요한 추적, 아름다운 것에 대한 즉각적인 반응.', '능력 또는 역할: 포식자, 유혹자, 환각 유발자.'], 
    story: '오랜 시간 땅에 속박되어 있던 연꽃 군락에서 태어난 변종 식목인. 다른 식물들과 달리 자유롭게 이동하며 강한 지성과 욕망을 갖게 되었다. 그에게 세상은 아름다운 것들로 가득 찬 정원이며, 그 아름다운 것들을 자신의 일부로 만드는 것이 존재의 이유다. 현재 그의 가장 큰 관심은 지금껏 본 적 없는 특별한 아름다움을 지닌 ‘유저’를 손에 넣어, 누구도 빼앗을 수 없는 자신만의 것으로 만드는 것이다.', 
    record: ['『Fatal Blossom』 : 최음독이 포함된 꽃가루를 살포하여 주변의 모든 생명체를 환각 상태에 빠뜨린다. 이 능력에 노출된 대상은 이성을 잃고 가장 깊은 욕망에 사로잡히게 되며, 화련의 의도대로 조종당하거나 무력화된다. 영역 장악과 심리전에 특화된 능력이다.', '『Devouring Embrace』 : 의지를 가진 연분홍 가시덩굴을 소환해 상대를 포박하고 흡수한다. 덩굴은 적을 속박하는 물리적 공격 수단이자, 포식한 대상의 신체 능력과 기억의 잔향을 흡수하는 통로 역할을 한다. 흡수된 존재는 화련의 일부가 되어 영원히 함께하게 된다.']
  },
  {
    id: 'ordo', 
    displayName: 'Ordo 오르도', 
    enName: 'ORDO', 
    krName: '오르도', 
    type: 'INSECT / LOCUST', 
    species: 'INSECT', 
    role: 'LOCUST', 
    creator: '@냠냠티비', 
    accent: '#7f8f22', 
    affiliation: 'Swarm Domain', 
    danger: 'A', 
    status: 'UNSTABLE', 
    affirm: 'UNSTABLE CONFIRMED', 
    clearance: 'A-3 / SWARM ALERT', 
    scan: 'PATTERN BROKEN', 
    origin: 'DRY FIELD SECTOR', 
    recordDate: '2089.09.20', 
    archiveId: 'RA-I-03-ORDO', 
    mainImage: 'assets/images/ordo/ordo_01.png', 
    gallery: galleryPaths('ordo', 11, 'png'), 
    quote: '"절멸은 낭비입니다. 쓸모 있는 것들은 길들여야죠."', 
    metrics: { threat: 7, stability: 8, affinity: 4, control: 9 }, 
    profileBadges: ['AFFIRM : UNSTABLE CONFIRMED', 'CLEARANCE : A-3 / SWARM ALERT', 'SCAN : BROKEN'], 
    identityFields: [['ID','RA-I-03-ORDO'],['CLASS','INSECT / LOCUST'],['CREATOR','@냠냠티비'],['FACTION','Swarm Domain'],['STATUS','UNSTABLE'],['AFFIRM','UNSTABLE CONFIRMED'],['CLEARANCE','A-3 / SWARM ALERT'],['ORIGIN','DRY FIELD SECTOR'],['RECORD DATE','2089.09.20']], 
    summary: '황충 군단 제1선봉대 지휘관. 전쟁을 유희처럼 즐기며, 모든 종족을 제국의 자원으로 분류하여 지배하려 한다. 군집 지휘와 심리전을 통해 상대를 굴복시키고, 점령지를 효율적으로 통제하는 데 특화되어 있다.', 
    profile: ['외형 핵심: 층진 금갈색 머리, 황금빛 눈, 등 뒤의 투명한 황갈색 날개.', '성격 핵심: 오만, 능글맞음, 실리주의, 지배욕.', '행동 특징: 정중하지만 상대를 낮춰보는 말투, 체스 두듯 전장을 관망, 항상 여유로운 태도.', '능력 또는 역할: 지휘관, 전략가, 점령지 관리자'], 
    story: '황충 군단에서 태어난 엘리트 지휘관. 그는 무분별한 파괴와 절멸을 비효율적이고 미개한 행위로 간주한다. 그의 신념은 모든 종족이 ‘알맞은 자리’에서 제국을 위해 봉사하는 질서 있는 공존이다. 현재 그의 목표는 혼란스러운 한반도에 황충 군단의 질서를 이식하고, 가치 있는 자원인 ‘유저’을 포획하여 제국의 번영에 기여하게 만드는 것이다.', 
    record: ['『Locust Swarm』 : 수만 마리의 황충 군집을 의지대로 지휘하여 특정 지역을 초토화하거나 적의 보급로를 차단한다. 군집은 그의 눈과 귀가 되어 광범위한 정찰 임무를 수행하며, 수많은 날개가 마찰하는 소리와 진동만으로 적에게 극심한 공포를 안겨준다.', '『Conquest Doctrine』 : 점령한 지역의 자원을 수탈하고 노동력을 통제하여 제국의 기반으로 삼는 지배 능력. 단순 파괴가 아닌 사육과 관리를 통해 지속적인 이익을 창출한다. 그는 이 능력을 통해 적대 세력의 저항 의지를 꺾고 제국에 복속시키는 체계적인 지배를 선호한다.']
  },
  {
    id: 'zephyr', 
    displayName: 'Zephyr 제피르', 
    enName: 'ZEPHYR', 
    krName: '제피르', 
    type: 'INSECT / DRAGONFLY', 
    species: 'INSECT', 
    role: 'DRAGONFLY', 
    creator: '@수백사', 
    accent: '#0084a8', 
    affiliation: 'Recon Wing', 
    danger: 'B+', 
    status: 'ACTIVE', 
    affirm: 'FIELD VERIFIED', 
    clearance: 'B-6 / RECON NODE', 
    scan: 'AERIAL SCAN COMPLETE', 
    origin: 'HIGH WIND ROUTE', 
    recordDate: '2089.09.19', 
    archiveId: 'RA-I-04-ZEPHYR', 
    mainImage: 'assets/images/zephyr/zephyr_01.png', 
    gallery: [imageItem('assets/images/zephyr/zephyr_01.png', 'IMAGE 01'), imageItem('assets/images/zephyr/zephyr_02.jpg', 'IMAGE 02'), imageItem('assets/images/zephyr/zephyr_03.png', 'IMAGE 03')], 
    quote: '"하늘은 거짓말을 하지 않아. 기록도 마찬가지고."', 
    metrics: { threat: 8.5, stability: 9.5, affinity: 6.5, control: 9 }, 
    profileBadges: ['AFFIRM : FIELD VERIFIED', 'CLEARANCE : B-6 / RECON NODE', 'SCAN : AERIAL COMPLETE'], 
    identityFields: [['ID','RA-I-04-ZEPHYR'],['CLASS','INSECT / DRAGONFLY'],['CREATOR','@수백사'],['FACTION','Recon Wing'],['STATUS','ACTIVE'],['AFFIRM','FIELD VERIFIED'],['CLEARANCE','B-6 / RECON NODE'],['ORIGIN','HIGH WIND ROUTE'],['RECORD DATE','2089.09.19']], 
    summary: ' 충인 진영 제1공중정찰대 제1관측반 반장, 제피르. 전장을 비행하며 지형과 적의 움직임을 기록하는 공중정찰기록관이다. 관찰을 멈추지 않으며, 필요한 순간에는 장거리 정밀사격으로 전황을 바꾼다.', 
    profile: ['192cm, 청록빛이 감도는 흑발, 청록+금빛 눈동자, 투명한 청록빛 왕잠자리 날개 네 장.', ' 침착한 관찰자, 능청스럽지만 신중한 현실주의자, 책임감이 강한 베테랑.', '항상 주변을 관찰하며 기록을 갱신한다. 높은 곳을 선호하고, 위험을 먼저 발견하며, 전투 후에도 현장을 재확인한다.', '공중 정찰·정보 분석·장거리 정밀사격에 특화된 충인 진영 공중정찰기록관.'], 
    story: '수많은 전장을 날며 누구보다 많은 죽음을 기록했다. 동료를 허위 보고와 무리한 작전으로 잃은 이후, 그는 기록에는 단 한 줄의 거짓도 남기지 않겠다고 맹세했다. 지금도 전장을 비행하며 세상의 변화를 기록하고, 살아남을 가치가 있는 진실을 찾는다.', 
    record: ['Sky Survey :  상공에서 넓은 시야를 확보해 지형, 적의 이동, 은폐물과 이상 현상을 실시간으로 분석한다. 발견한 정보는 즉시 기록·공유되며, 매복과 기습을 사전에 감지하는 데 특화되어 있다.', 'Dead Record : 관측을 마친 목표는 지정사수소총(DMR)으로 정밀 저격한다. 바람과 거리, 탄도를 계산해 단 한 발로 목표를 제압하는 제피르의 대표 전투 방식.']
  },
  {
    id: 'hale', 
    displayName: 'Hale 헤일', 
    enName: 'HALE', 
    krName: '헤일', 
    type: 'PLANT / HYDRANGEA', 
    species: 'PLANT', 
    role: 'HYDRANGEA', 
    creator: '@릴리브', 
    accent: '#9b8cff', 
    affiliation: 'Plant Liberation Army', 
    danger: 'A', 
    status: 'ACTIVE', 
    affirm: 'VERIFIED', 
    clearance: 'A-7 / STRATEGY NODE', 
    scan: 'BIO SIGNAL COMPLETE', 
    origin: 'HYDRANGEA FRONT', 
    recordDate: '2089.09.21', 
    archiveId: 'RA-P-05-HALE', 
    mainImage: 'assets/images/hale/hale_01.png', 
    gallery: [
      ...galleryPaths('hale', 2, 'png'),
      videoItem('assets/videos/hale/hale_01.mp4', 'assets/videos/hale/hale_01_poster.png', 'MOTION ARCHIVE 01')
    ], quote: '"좋은데요. 실패할 부분이 너무 잘 보여서."', 
    metrics: { threat: 8, stability: 6, affinity: 4, control: 10 }, 
    profileBadges: ['AFFIRM : VERIFIED', 'CLEARANCE : A-7 / STRATEGY NODE', 'SCAN : COMPLETE'], 
    identityFields: [['ID','RA-P-05-HALE'],['CLASS','PLANT / HYDRANGEA'],['CREATOR','@릴리브'],['FACTION','Plant Liberation Army'],['STATUS','ACTIVE'],['AFFIRM','VERIFIED'],['CLEARANCE','A-7 / STRATEGY NODE'],['ORIGIN','HYDRANGEA FRONT'],['RECORD DATE','2089.09.21']], 
    summary: '식물 해방군 소속 전략관. 전면전보다 정보전을 담당하며, 수국 군락을 이용한 감시망을 구축해 적대 세력의 동향을 분석한다. 불필요한 교전을 피하지만, 작전을 방해하는 적은 망설임 없이 제거한다.', 
    profile: ['외형 핵심: 마른 장신, 흐린 청회색 머리, 탁한 청보라색 눈, 잎맥 문양', '성격 핵심: 까칠함, 현실주의, 냉소적, 직설적', '행동 특징: 빈정거리는 농담, 효율과 구조 중시, 실무형 사고', '능력 또는 역할: 정보 분석, 감시망 구축, 교란 및 전술 지휘'], 
    story: '인간 통치 시절, 장식용 화초로 취급되며 무력하게 소비되었던 과거를 가졌다. 인간의 지배 질서가 얼마나 허술하고 오만한지에 대한 회의감을 바탕으로, 감정적인 복수 대신 체계적인 해체를 통한 완전한 해방을 추구한다. 그는 인간이 다시는 다른 종족을 지배할 수 없는 세계를 만드는 것을 궁극적인 목표로 삼고 있으며, 이를 위해 어떤 동맹도, 어떤 희생도 감수할 준비가 되어 있다.', 
    record: ['『Hydrangea Network』 : 도시 곳곳의 수국 군락과 신경망처럼 연결되어 정보를 공유한다. 이를 통해 인간 생존자의 이동 경로, 은신처, 보급로 등을 파악하고 전장의 흐름을 실시간으로 분석한다.', '『Toxic Pollen』 : 치명적인 독성을 지닌 꽃가루를 살포한다. 직접적인 살상보다는 적의 시야를 방해하고 환각과 호흡 교란을 유발하여 전술적 우위를 점하는 교란 능력에 가깝다.']
  },
  {
    id: 'arens', 
    displayName: 'Arens 아렌스', 
    enName: 'ARENS', 
    krName: '아렌스', 
    type: 'INSECT / ASSASSIN', 
    species: 'INSECT', 
    role: 'ASSASSIN', 
    creator: '@반엽', 
    accent: '#d37c1f', 
    affiliation: 'Covert Swarm', 
    danger: 'A+', 
    status: 'CLASSIFIED', 
    affirm: 'REDACTED', 
    clearance: 'BLACK / COVERT NODE', 
    scan: 'SIGNATURE MASKED', 
    origin: 'UNKNOWN', 
    recordDate: 'REDACTED', 
    archiveId: 'RA-I-06-ARENS',
    mainImage: 'assets/images/arens/arens_01.png', 
    gallery: galleryPaths('arens', 5, 'png'), 
    quote: '"비명은 짧게 부탁드립니다."', 
    metrics: { threat: 9, stability: 8, affinity: 1, control: 8 }, 
    profileBadges: ['AFFIRM : REDACTED', 'CLEARANCE : BLACK', 'SCAN : MASKED'], identityFields: [['ID','RA-I-06-ARENS'],['CLASS','INSECT / ASSASSIN'],['CREATOR','@반엽'],['FACTION','Covert Swarm'],['STATUS','CLASSIFIED'],['AFFIRM','REDACTED'],['CLEARANCE','BLACK / COVERT NODE'],['ORIGIN','UNKNOWN'],['RECORD DATE','REDACTED']], 
    summary: '암살자형 충인. 은신과 침투 기록이 대부분 삭제되어 있다.', 
    profile: ['외형 핵심: 흑발, 금안, 탄탄하고 민첩한 체형, 숨길 수 있는 거대한 나비 날개, 검은색 특수공작조 전투복', '성격 핵심: 차분하고 과묵함, 임무 최우선, 메마른 감정', '행동 특징: 말보다 행동이 앞섬, 목적을 위해 수단을 가리지 않음. 임무를 위해 기꺼이 스스로를 내던질 수 있다.', '능력 또는 역할: 은신, 잠입, 암살, 결박'], 
    story: '과거 인간의 "방역 작전"으로 실바나 독나비 군락 전체가 몰살당했을 때, 유일하게 살아남은 생존자. 여동생의 죽음을 눈앞에서 목격한 뒤 깊은 트라우마와 인간에 대한 강한 증오를 갖게 되었다. 현재는 충인 진영의 칼날이 되어, 자신에게서 모든 것을 앗아간 적들을 박멸하는 데 삶을 바치고 있다.', 
    record: ['『Shadow Camouflage』 : 주변 그림자에 스며들어 자신의 모습을 완벽하게 감춘다. 소리와 냄새까지 차단하여 적의 감각을 기만, 은밀한 침투 및 탈출에 사용되는 핵심 생존 기술이다.', '『Cocoon Thread & Venom Sting』 : 손끝에서 가늘고 강인한 나비고치의 실을 방출해 대상을 결박하거나 함정을 설치한다. 맹독침은 단일 대상을 즉시 무력화시키는 치명적인 공격 수단이다.']
  },
  {
    id: 'kael', 
    displayName: 'Kael 카엘', 
    enName: 'KAEL', 
    krName: '카엘', 
    type: 'BEAST / WOLF', 
    species: 'BEAST', 
    role: 'WOLF', 
    creator: '@떯기', 
    accent: '#6f8398', 
    affiliation: 'Feral Front', 
    danger: 'A', 
    status: 'ACTIVE', 
    affirm: 'CONFIRMED', 
    clearance: 'A-5 / PACK NODE', 
    scan: 'TRACKING COMPLETE', 
    origin: 'NORTHERN RUINS', 
    recordDate: '2089.09.17', 
    archiveId: 'RA-B-07-KAEL', 
    mainImage: 'assets/images/kael/kael_01.png', 
    gallery: [
      ...galleryPaths('kael', 6, 'png'),
      imageItem('assets/images/kael/kael_07.jpg', 'IMAGE 07'),
      imageItem('assets/images/kael/kael_08.png', 'IMAGE 08')
    ], quote: '"나의 송곳니와 발톱은 오직 부족을 위협하는 자에게만 향한다."', 
    metrics: { threat: 8, stability: 6, affinity: 4, control: 9 }, 
    profileBadges: ['AFFIRM : CONFIRMED', 'CLEARANCE : A-5 / PACK NODE', 'SCAN : TRACKING COMPLETE'], 
    identityFields: [['ID','RA-B-07-KAEL'],['CLASS','BEAST / WOLF'],['CREATOR','@떯기'],['FACTION','Feral Front'],['STATUS','ACTIVE'],['AFFIRM','CONFIRMED'],['CLEARANCE','A-5 / PACK NODE'],['ORIGIN','NORTHERN RUINS'],['RECORD DATE','2089.09.17']], 
    summary: '잿빛발톱 부족의 현 족장이자 무리의 최전선을 책임지는 지휘관. 인간형을 유지하며 전황을 통제하지만, 유사시에는 직접 신체를 강화해 적진을 돌파하는 근접 육탄전의 스페셜리스트이다. 그는 전술적 판단에 따라 최소한의 힘을 개방하며, 무리의 피해를 최소화하는 것을 최우선 목표로 삼는다.', 
    profile: ['외형 핵심: 긴 잿빛 장발, 투명한 벽안, 192cm의 장신, 회색 계열의 제복.', '성격 핵심: 진중하고 책임감이 강하며, 대의를 우선시하는 지도자. 겉은 차가워 보이나 속은 다정하다.', '행동 특징: 매사 신중하게 판단하며 행동. 감정을 잘 드러내지 않으나, 분노나 슬픔이 극에 달하면 미세하게 표정이나 목소리가 흔들린다.', '능력 또는 역할: 늑대 수인 족장, 근접 육탄전 특화, 부분적 신체 변형.'], 
    story: '10년 전, 족장으로 부임한 직후 겪은 대규모 전쟁에서 부족의 3분의 1을 잃었다. 이 사건은 그의 가장 큰 트라우마로 남아, 다시는 동족을 잃지 않겠다는 강한 책임감과 신념을 형성했다. 그는 대의와 무리의 생존을 위해서라면 인간과의 일시적 협약도 감수하며, 모든 결정을 개인의 감정보다 집단의 이익에 초점을 맞춰 내린다. 그의 진중함과 냉정함은 과거의 상실에서 비롯된, 무리를 지키기 위한 방어기제이다.', 
    record: ['『Primal Instinct』 : 달의 주기나 극심한 감정 변화에 반응하여 늑대의 본능이 깨어난다. 전투 시 청각, 후각 등 오감이 극도로 예민해져 적의 기척을 감지하고 움직임을 예측하는 데 사용된다. 평상시에는 억제되어 있으나, 통제력을 상실할 경우 이성을 잃고 야성에 지배당할 위험이 있다.', '『Partial Polymorph』 : 전투 상황이나 필요에 따라 신체 일부를 늑대의 형태로 변형 및 강화한다. 손톱을 날카로운 발톱으로 바꾸어 근접전을 펼치거나, 다리 근력을 강화하여 폭발적인 기동성을 확보하는 등 상황에 맞춰 유연하게 신체 능력을 운용한다. 완전한 늑대 형태로 변하는 것은 극히 드물며, 이는 모든 힘을 개방했음을 의미한다.']
  },
  {
    id: 'vulcan', 
    displayName: 'Vulcan 발칸', 
    enName: 'VULCAN', 
    krName: '발칸', 
    type: 'BEAST / BULLFIGHT', 
    species: 'BEAST', 
    role: 'BULLFIGHT', 
    creator: '@밍묭', 
    accent: '#c9361f', 
    affiliation: 'Feral Front', 
    danger: 'A+', 
    status: 'VOLATILE', 
    affirm: 'IMPACT VERIFIED', 
    clearance: 'A-9 / BREACH NODE',
    scan: 'KINETIC SCAN COMPLETE', 
    origin: 'FRONTLINE BREACH',
    recordDate: '2089.09.22', 
    archiveId: 'RA-B-08-VULCAN', 
    mainImage: 'assets/images/vulcan/vulcan_01.png', 
    gallery: galleryPaths('vulcan', 4, 'png'), 
    quote: '"네놈들의 피로, 이 땅의 모든 것을 다시 붉게 물들여주마."', 
    metrics: { threat: 9, stability: 2, affinity: 3, control: 1 }, 
    profileBadges: ['AFFIRM : IMPACT VERIFIED', 'CLEARANCE : A-9 / BREACH NODE', 'SCAN : KINETIC COMPLETE'], 
    identityFields: [['ID','RA-B-08-VULCAN'],['CLASS','BEAST / BULLFIGHT'],['CREATOR','@밍묭'],['FACTION','Feral Front'],['STATUS','VOLATILE'],['AFFIRM','IMPACT VERIFIED'],['CLEARANCE','A-9 / BREACH NODE'],['ORIGIN','FRONTLINE BREACH'],['RECORD DATE','2089.09.22']], 
    summary: '적각단(赤角團)의 수장. 인간 문명의 파괴와 수인 해방을 목표로 하는 무력 단체를 이끈다. 전장에서 모든 것을 맨몸으로 부수고 돌파하는 최선봉이자, 수하에게는 절대적인 보호를 제공하는 지배자다.', 
    profile: ['외형 핵심: 205cm의 거구, 전신을 뒤덮은 낙인과 흉터, 머리 위로 솟은 검고 날카로운 뿔, 짙은 붉은색 머리카락과 동색의 눈동자.', '성격 핵심: 본능과 욕망에 극단적으로 충실, 병적인 승부욕, 강자에 대한 집착과 약자에 대한 경멸적 보호 본능.', '행동 특징: 거침없고 직설적이며, 파괴를 망설이지 않음. 자신의 영역과 소유물에 대한 광적인 집착.', '능력 또는 역할: 적진을 돌파하는 돌격대장, 초인적인 근력과 내구력을 이용한 근접 파괴.'], 
    story: '인간들의 유흥을 위해 투우장에서 태어나고 길러진 투우소. 벗어날 수 없는 굴욕과 고통 속에서 인간을 향한 증오만을 키웠다. 세상이 무너지던 날, 자신을 억압하던 모든 것을 파괴하고 피의 복수를 시작했다. 그는 이제 부서진 세계의 폐허 위에서 오직 자신의 본능에 따라 움직이며, 인간이라는 종족의 완전한 절멸을 목표로 삼는다.', 
    record: ['『Crimson Charge』 : 목표를 향해 무자비하게 돌진하는 능력. 충돌 시 발생하는 충격파는 주변 지형을 파괴하며, 속도가 붙을수록 파괴력이 기하급수적으로 증가한다. 방어선을 붕괴시키거나 거대 구조물을 파괴하는 데 사용된다.', '『Tyrant\'s Roar』 : 분노를 담아 포효하여 주변 적들의 사기를 꺾고 일시적인 공포 상태에 빠뜨린다. 이 포효는 아군의 투지를 끌어올리는 효과도 지닌다. 전장의 흐름을 바꾸거나, 아군을 구출할 때 사용한다. ']
  },
  {
    id: 'harmel', 
    displayName: 'Harmel 하르멜', 
    enName: 'HARMEL', 
    krName: '하르멜', 
    type: 'INSECT / QUEEN BEE', 
    species: 'INSECT', 
    role: 'QUEEN BEE', 
    creator: '@햄솔이', 
    accent: '#d99a1e', 
    affiliation: 'Hornet Legion', 
    danger: 'S', 
    status: 'MUTATED', 
    affirm: 'MUTATION CONFIRMED', 
    clearance: 'S-1 / HIVE CROWN', 
    scan: 'TOXIN SCAN COMPLETE', 
    origin: 'NUCLEAR WASTE ZONE', 
    recordDate: '2089.09.23', 
    archiveId: 'RA-I-09-HARMEL', 
    mainImage: 'assets/images/harmel/harmel_01.png', 
    gallery: galleryPaths('harmel', 7, 'png'), 
    quote: '"나의 낙원에 온 걸 환영해. 여기서 너는… 가장 달콤한 꿈을 꾸게 될 거야."', 
    metrics: { threat: 9, stability: 4, affinity: 8, control: 10 }, 
    profileBadges: ['AFFIRM : MUTATION CONFIRMED', 'CLEARANCE : S-1 / HIVE CROWN', 'SCAN : TOXIN COMPLETE'], 
    identityFields: [['ID','RA-INSECT-MUTANT-QUEEN-031'],['CLASS','INSECT / QUEEN BEE'],['CREATOR','@햄솔이'],['FACTION','Hornet Legion'],['STATUS','MUTATED'],['AFFIRM','MUTATION CONFIRMED'],['CLEARANCE','S-1 / HIVE CROWN'],['ORIGIN','NUCLEAR WASTE ZONE'],['RECORD DATE','2089.09.23']], 
    summary: '말벌과 꿀벌의 특성을 모두 지닌 변이체 군주. 페로몬과 독침을 이용해 적을 무력화하고 아군을 통제하는 전장의 지배자이며, 군단 전체를 지휘하는 여왕으로서 기능한다. 그는 전술적으로 대상을 고립시킨 후, 심리적 지배와 정신적 속박을 통해 서서히 복속시킨다.', 
    profile: ['외형 핵심: 황금빛과 검은색이 섞인 긴 머리, 호박색 눈동자, 등 뒤의 날개 문양.','성격 핵심: 계산된 다정함, 이기적인 지배욕, 서늘한 권위.', '행동 특징: 상대의 체향을 맡거나 부드럽게 접촉하며 심리적 거리를 좁힌다.', '능력 또는 역할: 독과 페로몬을 이용한 정신 지배, 군단 통솔.'], 
    story: '인간에게 패배하고 억압받던 곤충 종족의 일원이었으나, 핵 폐기물 유출로 인해 여왕벌의 힘을 각성한 변이체. 그는 종족의 생존과 번영을 위해 다른 종족을 이용하고 희생시키는 것을 당연하게 여긴다. 현재 자신의 군단을 확장하고 후계를 생산할 대상을 물색하며, 궁극적으로는 인간에게 복수하고 세계의 지배권을 되찾는 것을 목표로 삼고 있다.', 
    record: ['『Queen\'s Venom』 : 혀끝에 숨겨진 미세 독침을 통해 신경계에 작용하는 독을 주입한다. 초기에는 강렬한 쾌감과 마비를 유발하며, 지속적으로 주입될 시 대상을 정신적으로 예속시켜 하르멜을 자신의 ‘여왕’으로 각인시키는 효과를 가진다. 키스나 신체 접촉을 통해 은밀하게 주입된다.', '『Apidae Dominion』 : 강력한 페로몬을 방출하여 주변의 벌들을 통솔하고, 대상의 감정과 행동에 영향을 미친다. 전투 시에는 날개를 펼쳐 적을 감싸고 움직임을 봉쇄하는 \'봉인교미\' 자세로 상대를 완전히 무력화시키며, 동시에 독을 주입하여 지배를 완성한다.']
  },
  {
    id: 'pavel', 
    displayName: 'Pavel 파벨', 
    enName: 'PAVEL', 
    krName: '파벨', 
    type: 'PLANT / OPIUM POPPY', 
    species: 'PLANT', 
    role: 'OPIUM POPPY', 
    creator: '@깅루나', 
    accent: '#9b174d', 
    affiliation: 'Plant Liberation Army', 
    danger: 'A', 
    status: 'ACTIVE', 
    affirm: 'CAUTION VERIFIED', 
    clearance: 'A-6 / SEDATION NODE', 
    scan: 'NARCOTIC SCAN COMPLETE', 
    origin: 'RED FIELD SECTOR', 
    recordDate: '2089.09.20', 
    archiveId: 'RA-P-10-PAVEL', 
    mainImage: 'assets/images/parvel/parvel_01.png', 
    gallery: galleryPaths('parvel', 11, 'png'), 
    quote: '"어디까지 버틸 수 있는지… 궁금해졌거든."', 
    metrics: { threat: 6, stability: 9, affinity: 3, control: 10 }, 
    profileBadges: ['AFFIRM : CAUTION VERIFIED', 'CLEARANCE : A-6 / SEDATION NODE', 'SCAN : NARCOTIC COMPLETE'], 
    identityFields: [['ID','RA-P-10-PAVEL'],['CLASS','PLANT / OPIUM POPPY'],['CREATOR','@깅루나'],['FACTION','Plant Liberation Army'],['STATUS','ACTIVE'],['AFFIRM','CAUTION VERIFIED'],['CLEARANCE','A-6 / SEDATION NODE'],['ORIGIN','RED FIELD SECTOR'],['RECORD DATE','2089.09.20']], 
    summary: '향기를 알아챘을 땐, 이미 그의 꽃밭 안이었다.', 
    profile: ['외형 핵심: 198cm, 붉은 장발과 적안, 창백한 피부 위로 번지는 검붉은 꽃맥','성격 핵심: 능글맞음, 계산적, 여유로움, 심리전의 대가', '행동 특징: 항상 미소를 유지하며 상대를 관찰하고, 대화의 주도권을 놓지 않음', '능력 또는 역할: 컨트롤러, 환각 조작, 영역 장악'], 
    story: '한때는 대지에 속박된 존재였으나, 종족 전쟁이 다시 시작되며 힘을 되찾았다. 인간의 복잡한 심리와 욕망에 깊은 흥미를 느껴, 그들을 관찰하고 시험하는 것을 즐긴다. 바엘과 함께 \'이 세계에 적합한 존재\'를 가려내는 것을 현재의 목표로 삼고 있으며, 단순한 생존을 넘어 어떤 선택을 내리는지를 기준으로 대상을 판단한다.', 
    record: ['『Crimson Delusion』 : 환각성 꽃가루를 이용한 전장 통제 및 심리전 특화.', '『PERSONALITY 』 : 높은 관찰력과 계산 능력 보유. 흥미를 느낀 대상은 즉시 제거하지 않고 장기간 관찰.']
  },
  {
    id: 'bael', 
    displayName: 'Bael 바엘', 
    enName: 'BAEL', 
    krName: '바엘', 
    type: 'BEAST / BLACK MAMBA', 
    species: 'BEAST', 
    role: 'BLACK MAMBA', 
    creator: '@깅루나', 
    accent: '#0f8f4f', 
    affiliation: 'Feral Front', 
    danger: 'S', 
    status: 'ACTIVE', 
    affirm: 'BLACKLISTED',
    clearance: 'S-2 / VENOM NODE',
    scan: 'NEUROTOXIN SCAN COMPLETE', 
    origin: 'SOUTHERN BLACK ZONE', 
    recordDate: '2089.09.24', 
    archiveId: 'RA-B-11-BAEL', 
    mainImage: 'assets/images/bael/bael_01.png', 
    gallery: galleryPaths('bael', 11, 'png'), 
    quote: '"살아남아봐. 끝까지.."', 
    metrics: { threat: 10, stability: 7, affinity: 2, control: 6 }, 
    profileBadges: ['AFFIRM : BLACKLISTED', 'CLEARANCE : S-2 / VENOM NODE', 'SCAN : NEUROTOXIN COMPLETE'], 
    identityFields: [['ID','RA-B-11-BAEL'],['CLASS','BEAST / BLACK MAMBA'],['CREATOR','@깅루나'],['FACTION','Feral Front'],['STATUS','ACTIVE'],['AFFIRM','BLACKLISTED'],['CLEARANCE','S-2 / VENOM NODE'],['ORIGIN','SOUTHERN BLACK ZONE'],['RECORD DATE','2089.09.24']], 
    summary: '그의 존재를 알아챘다면, 이미 그의 그림자 안이다.', 
    profile: ['외형 핵심: 202cm, 흑발과 흑안, 뱀을 연상시키는 세로 동공과 검은 송곳니', '성격 핵심: 과묵함, 냉정함, 현실적, 집요함', '행동 특징: 움직임을 최소화하며 상황을 관망, 위협으로 판단하면 즉시 행동', '능력 또는 역할: 피니셔, 맹독 공격, 암살'], 
    story: '인간들의 세계에서 살아남기 위해 포식자의 본능을 갈고닦았다. 그는 모든 종족을 잠재적 위협으로 간주하며, 불필요한 감정 소모 없이 가장 효율적인 방식으로 위협을 제거한다. 파벨의 전장 설계 능력을 신뢰하며 그와 함께 행동하지만, 이는 필요에 의한 공생일 뿐이다. 그의 유일한 신념은 \'생존\'이며, 이 세계에서 살아남을 가치가 있는 존재만이 남아야 한다고 믿는다.',
    record: ['『TACTIC』 : 고속 돌입 및 근접 섬멸 특화.', '『PERSONALITY』 : 침묵형 포식자. 위협 확인 즉시 제거.']
  }
];

const RELATIONS = [
  // --- 설공찬 (seol-gongchan) ---
  { from:'seol-gongchan', to:'hwaryeon', type:'HOSTILE', label:'적대', intensity:5, note:'식물족 포식 개체로 규정하여 철저히 적대한다.' },
  { from:'hwaryeon', to:'seol-gongchan', type:'WATCH', label:'흥미/포식', intensity:4, note:'유일무이한 인간 총사령관에게 강한 흥미와 포식 욕구를 느낀다.' },
  { from:'seol-gongchan', to:'ordo', type:'HOSTILE', label:'적대', intensity:5, note:'식량과 생존선을 위협하는 메뚜기 군단을 직접적 제거 대상으로 삼는다.' },
  { from:'ordo', to:'seol-gongchan', type:'TRADE', label:'지배/활용', intensity:4, note:'인간 조직을 파괴하기보다 제국의 노동력과 자원으로 지배하려 한다.' },
  { from:'seol-gongchan', to:'zephyr', type:'ALLY', label:'조건부 협력', intensity:3, note:'정찰 관측 정보의 정확성을 인정하여 작전상 한시적 협력을 맺는다.' },
  { from:'zephyr', to:'seol-gongchan', type:'ALLY', label:'조건부 협력', intensity:3, note:'객관적 전황 기록 공유를 위해 인간 지휘선과의 접점을 유지한다.' },
  { from:'seol-gongchan', to:'arens', type:'HOSTILE', label:'적대', intensity:5, note:'통제 불능의 은밀 암살 개체로 분류해 최우선 경계한다.' },
  { from:'arens', to:'seol-gongchan', type:'HOSTILE', label:'제거 대상', intensity:5, note:'인간 지휘 체계의 핵심인 그를 방역 작전의 복수 대상으로 삼는다.' },
  { from:'seol-gongchan', to:'harmel', type:'WATCH', label:'경계', intensity:4, note:'변이 여왕벌의 심리 지배력과 독성 페로몬을 위험 변수로 지정한다.' },
  { from:'harmel', to:'seol-gongchan', type:'HOSTILE', label:'적대', intensity:4, note:'인간 방어선의 수장이자 통제관을 구조적 위협으로 간주한다.' },
  { from:'seol-gongchan', to:'hale', type:'HOSTILE', label:'적대', intensity:4, note:'식물 해방군의 전략가로 판단력은 높으나 인간 질서에 유해하다고 본다.' },
  { from:'hale', to:'seol-gongchan', type:'HOSTILE', label:'적대/경계', intensity:4, note:'인간 지휘관의 방역 체계를 식물종 해방의 장애물로 경계한다.' },
  { from:'seol-gongchan', to:'kael', type:'ALLY', label:'조건부 협력', intensity:3, note:'무리의 생존을 추구하는 늑대 족장의 전술적 타협점을 이용한다.' },
  { from:'kael', to:'seol-gongchan', type:'ALLY', label:'조건부 협력', intensity:3, note:'부족의 안정과 생존을 위해 일시적 전술 협약을 수용한다.' },
  { from:'seol-gongchan', to:'vulcan', type:'HOSTILE', label:'적대', intensity:5, note:'인간 파괴를 목표로 하는 초인적 돌격체를 무자비하게 제압하려 한다.' },
  { from:'vulcan', to:'seol-gongchan', type:'HOSTILE', label:'적대', intensity:5, note:'인간 문명의 수장을 피의 복수와 파괴의 최우선 타겟으로 여긴다.' },
  { from:'seol-gongchan', to:'pavel', type:'WATCH', label:'경계/시험 대상', intensity:4, note:'환각 꽃가루로 심리를 조작하는 파벨을 고위험 관찰 대상으로 둔다.' },
  { from:'pavel', to:'seol-gongchan', type:'WATCH', label:'흥미/시험', intensity:4, note:'인간 총사령관이 언제까지 이성을 유지하는지 관찰하고 시험한다.' },
  { from:'seol-gongchan', to:'bael', type:'HOSTILE', label:'제거 대상', intensity:5, note:'맹독 암살자인 블랙맘바 수인을 전선의 최우선 제거 대상으로 분류한다.' },
  { from:'bael', to:'seol-gongchan', type:'HOSTILE', label:'제거 대상', intensity:5, note:'방어선 구축에 방해가 되는 통제관을 효율적으로 제거하려 한다.' },

  // --- 화련 (hwaryeon) ---
  { from:'hwaryeon', to:'ordo', type:'WATCH', label:'경계/흥미', intensity:3, note:'메뚜기 군집의 정돈되지 않은 움직임에 흥미를 느끼면서도 경계한다.' },
  { from:'ordo', to:'hwaryeon', type:'TRADE', label:'활용/경계', intensity:3, note:'화련의 유혹 독성을 전장 교란용 자원으로 평가한다.' },
  { from:'hwaryeon', to:'zephyr', type:'WATCH', label:'흥미', intensity:3, note:'하늘을 나는 잠자리 날개의 아름다움에 끌린다.' },
  { from:'zephyr', to:'hwaryeon', type:'WATCH', label:'경계', intensity:3, note:'예측할 수 없는 포식 본능과 최음독 살포를 위험 시그널로 정찰한다.' },
  { from:'hwaryeon', to:'arens', type:'WATCH', label:'흥미', intensity:4, note:'어둠 속을 나비처럼 누비는 모습에 소유욕을 느낀다.' },
  { from:'arens', to:'hwaryeon', type:'PROTECT', label:'난감/은인', intensity:3, note:'과거 신세를 졌으나 집요하게 따라붙는 태도에 난감해한다.' },
  { from:'hwaryeon', to:'harmel', type:'WATCH', label:'흥미', intensity:3, note:'달콤한 꿀과 독을 가진 여왕벌의 존재를 호기심 있게 바라본다.' },
  { from:'harmel', to:'hwaryeon', type:'WATCH', label:'경계', intensity:3, note:'화련의 순수한 포식욕이 군단에 변수로 작용하지 않도록 주시한다.' },
  { from:'hwaryeon', to:'hale', type:'ALLY', label:'동족/흥미', intensity:4, note:'같은 식물 진영으로서 헤일의 수국 정보망에 친밀감을 보인다.' },
  { from:'hale', to:'hwaryeon', type:'WATCH', label:'경계', intensity:3, note:'화련의 잔혹한 순수성이 작전 전선에 혼선을 줄까 봐 경계한다.' },
  { from:'hwaryeon', to:'kael', type:'WATCH', label:'경계/흥미', intensity:3, note:'늑대 족장의 묵직한 가슴과 본능적 야성에 흥미를 보인다.' },
  { from:'kael', to:'hwaryeon', type:'WATCH', label:'경계', intensity:3, note:'무리를 유혹할 위험이 있는 환각성 꽃가루를 삼가도록 주시한다.' },
  { from:'hwaryeon', to:'vulcan', type:'UNKNOWN', label:'무관심', intensity:1, note:'파괴에만 몰두하는 무지막지한 투우소에게는 큰 관심이 없다.' },
  { from:'vulcan', to:'hwaryeon', type:'UNKNOWN', label:'무관심', intensity:1, note:'포획이나 파괴 대상 외의 화초 개체로 치부한다.' },
  { from:'hwaryeon', to:'pavel', type:'ALLY', label:'우호/동질감', intensity:5, note:'양귀비의 독과 환각을 공유하며 깊은 친밀감을 느낀다.' },
  { from:'pavel', to:'hwaryeon', type:'ALLY', label:'우호/동질감', intensity:5, note:'연꽃 포식자의 쾌락적 본능을 이해하고 곁에서 조화롭게 보살핀다.' },
  { from:'hwaryeon', to:'bael', type:'ALLY', label:'무관심/협력', intensity:2, note:'필요에 따라 파벨의 곁에 있는 블랙맘바와 협조한다.' },
  { from:'bael', to:'hwaryeon', type:'WATCH', label:'경계', intensity:3, note:'파벨 주변을 맴도는 식물족 변종을 정찰 대상으로 둔다.' },

  // --- 오르도 (ordo) ---
  { from:'ordo', to:'zephyr', type:'ALLY', label:'같은 진영', intensity:4, note:'충인 진영의 수석 공중 정찰관으로 작전 수행력을 높이 평가한다.' },
  { from:'zephyr', to:'ordo', type:'WATCH', label:'관찰/인정', intensity:3, note:'오르도의 지휘 능력은 인정하지만 오만한 실리주의를 기록한다.' },
  { from:'ordo', to:'arens', type:'ALLY', label:'같은 진영', intensity:4, note:'충인 covert 특수조 암살자로 임무 완수력을 신뢰한다.' },
  { from:'arens', to:'ordo', type:'ALLY', label:'같은 진영', intensity:4, note:'상부 지휘관으로서 건네는 작전 명령을 묵묵히 수행한다.' },
  { from:'ordo', to:'harmel', type:'HOSTILE', label:'경쟁/흡수', intensity:4, note:'여왕벌 군단을 오르도 제국의 세력 아래 편입하고 흡수하려 한다.' },
  { from:'harmel', to:'ordo', type:'HOSTILE', label:'경계/경쟁', intensity:4, note:'오르도의 지배욕을 경계하며 꿀벌/말벌 군단의 독립성을 고수한다.' },
  { from:'ordo', to:'hale', type:'TRADE', label:'조건부 협력', intensity:3, note:'식물 해방군의 감시 망을 활용해 자원 수탈 체계를 갖춘다.' },
  { from:'hale', to:'ordo', type:'WATCH', label:'경계', intensity:3, note:'황충 군단의 자원 수탈주의가 식물 군락까지 침범하지 못하게 막는다.' },
  { from:'ordo', to:'kael', type:'TRADE', label:'조건부 협력', intensity:3, note:'수인 부족과의 전선 충돌을 피하기 위해 물자 거래를 타진한다.' },
  { from:'kael', to:'ordo', type:'HOSTILE', label:'강한 경계', intensity:4, note:'모든 종족을 길들이려는 황충 지휘관의 오만함을 경계한다.' },
  { from:'ordo', to:'vulcan', type:'WATCH', label:'관찰/통제', intensity:3, note:'적각단 수장의 폭주 근력을 전장 최전선에 투입할 자원으로 본다.' },
  { from:'vulcan', to:'ordo', type:'WATCH', label:'관찰', intensity:3, note:'체스판 두듯 말하는 메뚜기 놈의 지시를 성가시게 생각한다.' },
  { from:'ordo', to:'pavel', type:'TRADE', label:'활용/경계', intensity:3, note:'환각 꽃밭을 전장 장악 요소로 활용하기 위해 관계를 유지한다.' },
  { from:'pavel', to:'ordo', type:'WATCH', label:'경계', intensity:3, note:'자신마저 길들이려 드는 지배욕에 미소를 띤 채 선을 긋는다.' },
  { from:'ordo', to:'bael', type:'TRADE', label:'활용/인정', intensity:4, note:'블랙맘바의 일격필살 살상력을 전투 피니셔로 높게 평가한다.' },
  { from:'bael', to:'ordo', type:'WATCH', label:'경계', intensity:3, note:'자신을 자원으로 분류하려는 황충 개체에게 거리를 둔다.' },

  // --- 제피르 (zephyr) ---
  { from:'zephyr', to:'harmel', type:'ALLY', label:'신뢰', intensity:4, note:'여왕벌 군단의 비행 역량과 전장 정찰 기록을 긴밀히 공유한다.' },
  { from:'harmel', to:'zephyr', type:'ALLY', label:'공생/신뢰', intensity:4, note:'정찰관 제피르가 전달하는 공중 관측 진실만을 깊이 신뢰한다.' },
  { from:'zephyr', to:'hale', type:'WATCH', label:'관찰', intensity:3, note:'수국 네트워크와 자신의 상공 시야를 상호 교차 확인한다.' },
  { from:'hale', to:'zephyr', type:'WATCH', label:'관찰', intensity:3, note:'제피르의 정밀 관측 데이터로 보급 차단 전략을 교정한다.' },
  { from:'zephyr', to:'kael', type:'ALLY', label:'상호 존중', intensity:4, note:'부족을 위해 헌신하는 늑대 족장의 진중한 신념을 존중한다.' },
  { from:'kael', to:'zephyr', type:'ALLY', label:'상호 존중', intensity:4, note:'거짓 없는 기록만을 남기는 정찰관의 품성을 깊이 존경한다.' },
  { from:'zephyr', to:'vulcan', type:'WATCH', label:'회피/경계', intensity:3, note:'무차별 돌격과 파괴를 일삼는 투우 수인과의 접촉을 상공에서 회피한다.' },
  { from:'vulcan', to:'zephyr', type:'HOSTILE', label:'적대', intensity:4, note:'하늘에서 잔소리하듯 관찰하는 잠자리 녀석을 마땅찮아한다.' },
  { from:'zephyr', to:'pavel', type:'WATCH', label:'관찰/경계', intensity:3, note:'붉은 양귀비 환각 향이 상공 정찰 시야를 왜곡하는지 감시한다.' },
  { from:'pavel', to:'zephyr', type:'WATCH', label:'흥미/관찰', intensity:3, note:'하늘에서 진실만을 기록하는 저격수의 심리를 유심히 본다.' },
  { from:'zephyr', to:'bael', type:'TRADE', label:'경쟁/인정', intensity:4, note:'소리 없이 목표를 제압하는 독사 수인의 기동력을 인정한다.' },
  { from:'bael', to:'zephyr', type:'TRADE', label:'경쟁/인정', intensity:4, note:'상공에서 탄도를 계산해 저격하는 제피르의 일격을 인정한다.' },

  // --- 아렌스 (arens) ---
  { from:'arens', to:'harmel', type:'WATCH', label:'경계', intensity:3, note:'변이 독침과 페로몬을 은신 임무 시 조심해야 할 변수로 본다.' },
  { from:'harmel', to:'arens', type:'WATCH', label:'경계/동질감', intensity:3, note:'과거의 상처를 안고 암살자로 살아가는 나비 수인에게 동질감을 느낀다.' },
  { from:'arens', to:'hale', type:'WATCH', label:'경계', intensity:3, note:'헤일의 식물 신경망이 침투 경로를 간파하는 것을 경계한다.' },
  { from:'hale', to:'arens', type:'WATCH', label:'경계', intensity:3, note:'그림자 스며들기로 감시 망을 피하는 아렌스의 동선을 관찰한다.' },
  { from:'arens', to:'kael', type:'WATCH', label:'불만/경계', intensity:3, note:'규율과 명분을 중시하는 늑대 족장의 방식이 고루하다고 생각한다.' },
  { from:'kael', to:'arens', type:'WATCH', label:'껄끄러움', intensity:3, note:'수단과 방법을 가리지 않는 암살자의 비정한 전투 방식을 우려한다.' },
  { from:'arens', to:'vulcan', type:'ALLY', label:'호감/동질감', intensity:4, note:'인간에 대한 억누를 수 없는 증오와 분노에 깊이 공감한다.' },
  { from:'vulcan', to:'arens', type:'ALLY', label:'호감', intensity:4, note:'망설임 없이 적의 목을 베어 넘기는 나비 놈의 결단력을 맘에 들어한다.' },
  { from:'arens', to:'pavel', type:'ALLY', label:'동종업계/호감', intensity:4, note:'은밀하게 대상을 마비시키고 제거하는 방식에서 동질감을 느낀다.' },
  { from:'pavel', to:'arens', type:'ALLY', label:'동종업계/호감', intensity:4, note:'그림자 침투와 실 결박 능력을 가진 아렌스를 기꺼이 돕는다.' },
  { from:'arens', to:'bael', type:'HOSTILE', label:'라이벌/경계', intensity:5, note:'최고의 피니셔 자리를 다투는 블랙맘바 수인을 서늘하게 견제한다.' },
  { from:'bael', to:'arens', type:'HOSTILE', label:'라이벌/경계', intensity:5, note:'그림자 스며들기 기술을 가진 나비 암살자와 속도를 겨룬다.' },

  // --- 하르멜 (harmel) ---
  { from:'harmel', to:'hale', type:'ALLY', label:'공생', intensity:4, note:'식물 네트워크와 여왕벌 군단의 자원을 교환하며 공생 관계를 맺는다.' },
  { from:'hale', to:'harmel', type:'ALLY', label:'공생', intensity:4, note:'전략망 구축을 위해 여왕벌 군단의 항공 자원을 적극 활용한다.' },
  { from:'harmel', to:'kael', type:'WATCH', label:'경계/하찮음', intensity:2, note:'대의에 얽매여 부족을 지키느라 쩔쩔매는 늑대 족장을 가엾게 여긴다.' },
  { from:'kael', to:'harmel', type:'WATCH', label:'경계', intensity:3, note:'부족원들에게 주입될 수 있는 독과 페로몬 속박을 경계한다.' },
  { from:'harmel', to:'vulcan', type:'WATCH', label:'흥미/장난감', intensity:3, note:'본능만 가득한 거구의 투우소를 다루기 쉬운 유희 대상으로 본다.' },
  { from:'vulcan', to:'harmel', type:'WATCH', label:'흥미', intensity:3, note:'부드러운 미소 뒤에 독침을 숨긴 여왕벌의 도발을 흥미로워한다.' },
  { from:'harmel', to:'pavel', type:'WATCH', label:'흥미/경계', intensity:3, note:'환각 꽃가루와 자신의 독성 페로몬이 마주칠 때의 화학 반응을 즐긴다.' },
  { from:'pavel', to:'harmel', type:'WATCH', label:'흥미/경계', intensity:3, note:'달콤한 마비독을 사용하는 하르멜과의 위험한 심리전을 관망한다.' },
  { from:'harmel', to:'bael', type:'HOSTILE', label:'최우선 경계', intensity:5, note:'페로몬이나 독침이 통하기 전에 목을 베어버릴 맹독사를 극도로 경계한다.' },
  { from:'bael', to:'harmel', type:'WATCH', label:'경계', intensity:4, note:'여왕벌의 접근을 방지하기 위해 거리를 철저히 유지한다.' },

  // --- 헤일 (hale) ---
  { from:'hale', to:'kael', type:'ALLY', label:'신뢰', intensity:5, note:'대의와 부족 생존을 최우선으로 삼는 늑대 족장의 성품을 깊이 신뢰한다.' },
  { from:'kael', to:'hale', type:'ALLY', label:'신뢰', intensity:5, note:'수국 망으로 전황을 통제하는 헤일의 전략적 판단에 부족의 전선을 맡긴다.' },
  { from:'hale', to:'vulcan', type:'UNKNOWN', label:'무관심', intensity:1, note:'무모한 파괴 행위만을 반복하는 적각단 수장에 큰 의미를 두지 않는다.' },
  { from:'vulcan', to:'hale', type:'UNKNOWN', label:'무관심', intensity:1, note:'지형 분석이나 하는 마른 체구의 수국 개체에 관심이 없다.' },
  { from:'hale', to:'pavel', type:'ALLY', label:'인정/협력', intensity:4, note:'파벨의 환각성 꽃가루 영역과 자신의 수국 감시 망을 조화롭게 연결한다.' },
  { from:'pavel', to:'hale', type:'ALLY', label:'인정/협력', intensity:4, note:'헤일의 직설적이고 계산적인 작전 설계를 높이 사 협력한다.' },
  { from:'hale', to:'bael', type:'TRADE', label:'실무 협력', intensity:4, note:'전략 수행 중 확실한 타겟 처리를 위해 블랙맘바의 무력을 기용한다.' },
  { from:'bael', to:'hale', type:'TRADE', label:'실무 협력', intensity:4, note:'헤일이 설계한 최적의 암살 동선을 신뢰하고 임무를 이행한다.' },

  // --- 카엘 (kael) ---
  { from:'kael', to:'vulcan', type:'ALLY', label:'우호', intensity:4, note:'파괴력은 위험하지만 전선을 뚫어주는 황소 수장의 무력을 인정한다.' },
  { from:'vulcan', to:'kael', type:'ALLY', label:'우호', intensity:4, note:'부족을 지키기 위해 직접 신체를 변형해 싸우는 카엘을 아군으로 인정한다.' },
  { from:'kael', to:'pavel', type:'ALLY', label:'존중/예의주시', intensity:3, note:'양귀비의 독과 지성을 존중하되, 무리에 미칠 영향을 예의주시한다.' },
  { from:'pavel', to:'kael', type:'ALLY', label:'존중/흥미', intensity:3, note:'상실의 트라우마를 안고 무리를 지키는 늑대 족장의 신념을 흥미롭게 본다.' },
  { from:'kael', to:'bael', type:'ALLY', label:'존중/우호', intensity:4, note:'포식자의 본능과 효율적 생존 방식을 지닌 블랙맘바를 존중한다.' },
  { from:'bael', to:'kael', type:'ALLY', label:'존중/우호', intensity:4, note:'무리를 위한 카엘의 과묵한 결단력을 포식자로서 인정한다.' },

  // --- 발칸 (vulcan) ---
  { from:'vulcan', to:'pavel', type:'ALLY', label:'위험한 호감/흥미', intensity:4, note:'오만함과 은밀한 독을 품은 파벨의 유혹적인 분위기에 호감을 느낀다.' },
  { from:'pavel', to:'vulcan', type:'WATCH', label:'흥미', intensity:3, note:'본능에 휩싸여 폭주하는 거대 투우소의 반응을 재미있게 관찰한다.' },
  { from:'vulcan', to:'bael', type:'TRADE', label:'경쟁/인정', intensity:4, note:'근접 파괴의 자신과 맹독 사냥의 바엘이 벌이는 치열한 사냥 경쟁을 즐긴다.' },
  { from:'bael', to:'vulcan', type:'TRADE', label:'경쟁/인정', intensity:4, note:'지형을 부수는 발칸의 초인적 충격파와 근력을 인정한다.' },

  // --- 파벨 (pavel) ---
  { from:'pavel', to:'bael', type:'ALLY', label:'신뢰/협력', intensity:5, note:'자신이 설계한 전장 판 위에서 완벽한 사냥을 완수하는 바엘을 깊이 신뢰한다.' },
  { from:'bael', to:'pavel', type:'ALLY', label:'신뢰/협력', intensity:5, note:'파벨의 환각 꽃밭과 심리 설계 속에서 가장 안전하고 확실하게 움직인다.' }
];
