const BGM_TRACKS = [
{ title: '01.RUST ARK', mood: 'world map', src: 'assets/audio/bgm/01.RUST ARK(세계관).mp3' },
{ title: '01_1.RUST ARK', mood: 'world map', src: 'assets/audio/bgm/01_1.RUST ARK_2.mp3' },
{ title: '01_2.RUST ARK', mood: 'world map', src: 'assets/audio/bgm/01_2.RUST ARK_3.mp3' },
{ title: '02.last-transmission1(인간)', mood: 'human-being', src: 'assets/audio/bgm/02.last-transmission1(인간).mp3' },
{ title: '03.protocol_survive(인간)', mood: 'human-being', src: 'assets/audio/bgm/03.protocol_survive(인간).mp3' },
{ title: '04.BLACK SKY_FORMATION(충인)', mood: 'insect-human', src: 'assets/audio/bgm/04.BLACK SKY_FORMATION(충인).mp3' },
{ title: '05.swarm(충인)', mood: 'insect-human', src: 'assets/audio/bgm/05.swarm(충인).mp3' },
{ title: '06.primal(수인).', mood: 'primal', src: 'assets/audio/bgm/06.primal(수인).mp3' },
{ title: '07.reversion_apex(수인)', mood: 'primal', src: 'assets/audio/bgm/07.reversion_apex(수인).mp3' },
{ title: '08.RECLAMATION_ASPHALT BLOOM(식목인)', mood: 'plant', src: 'assets/audio/bgm/08.RECLAMATION_ASPHALT BLOOM(식목인).mp3' },
{ title: '09.verdant(식목인)', mood: 'plant', src: 'assets/audio/bgm/09.verdant(식목인).mp3' },
{ title: '10.gongchan', mood: 'human', src: 'assets/audio/bgm/10.gongchan.mp3' },
{ title: '11.hwaryeon', mood: 'plant', src: 'assets/audio/bgm/11.hwaryeon.mp3' },
{ title: '12.ordo', mood: 'insect', src: 'assets/audio/bgm/12.ordo.mp3' },
{ title: '13.arens', mood: 'insect', src: 'assets/audio/bgm/13.arens.mp3' },
{ title: '14.hale', mood: 'plant', src: 'assets/audio/bgm/14.hale.mp3' },
{ title: '15.harmel', mood: 'insect', src: 'assets/audio/bgm/15.harmel.mp3' },
{ title: '16.kael', mood: 'primal', src: 'assets/audio/bgm/16.kael.mp3' },
{ title: '17.red-bloom-black-fang', mood: 'plant&primal', src: 'assets/audio/bgm/17.red-bloom-black-fang.mp3' },
{ title: '18.bael', mood: 'primal', src: 'assets/audio/bgm/18.bael.mp3' },
{ title: '19.pavel', mood: 'plant', src: 'assets/audio/bgm/19.pavel.mp3' },
{ title: '20.vulcan', mood: 'primal', src: 'assets/audio/bgm/20.vulcan.mp3' },
{ title: '21.Zephyr', mood: 'insect', src: 'assets/audio/bgm/21.Zephyr.mp3' }
];

// 갤러리는 캐릭터마다 자유롭게 바꿀 수 있습니다.
// 이미지는 PNG만 사용합니다. 영상은 MP4 + poster PNG 조합을 권장합니다.
// 5장이면 galleryPaths('hale', 5), 10장이면 galleryPaths('hale', 10)으로 바꾸면 됩니다.
// 영상은 videoItem('assets/videos/hale/hale_01.mp4', 'assets/videos/hale/hale_01_poster.png', 'Motion Archive')처럼 추가합니다.
const imageItem = (src, title = 'Image Archive') => ({
  type: 'image',
  src,
  thumb: src,
  title
});

const videoItem = (src, thumb, title = 'Motion Archive') => ({
  type: 'video',
  src,
  thumb,
  title
});

const galleryPaths = (id, count = 6, ext = 'png') =>
  Array.from({ length: count }, (_, i) => imageItem(`assets/images/${id}/${id}_${String(i + 1).padStart(2, '0')}.${ext}`, `IMAGE ${String(i + 1).padStart(2, '0')}`));

const WORLD = {
  title: 'RUST ARK',
  logo: 'assets/images/common/rustark-hero-logo.png',
  subtitle: '2089 AFTERMATH / RESTRICTED BIO ARCHIVE',
  tagline: '인간은 자연을 지배한 것이 아니라, 전쟁에서 승리했을 뿐이다.',
  summary: '오래전 인간은 동물, 곤충, 식물과의 종족 전쟁에서 승리하고 수백 년간 세계를 통제했다. 그러나 2089년, 버려진 자연의 후손들은 다시 인간의 질서 밖에서 깨어났다. RUST ARK는 그 재전쟁 이후 남겨진 생체 기록 보관소다.',
  factions: [
    { name:'HUMAN', label:'COMMAND STRUCTURE', text:'승리 이후 세계를 관리해온 인간 중심 질서. 현재는 방어와 통제를 동시에 수행한다.' },
    { name:'PLANT', label:'ROOT NETWORK', text:'느린 성장과 깊은 기억을 무기로 삼는 식목인 세력. 해방과 복원을 명분으로 움직인다.' },
    { name:'INSECT', label:'SWARM DOMAIN', text:'군집, 정찰, 독성, 변이를 기반으로 빠르게 확산하는 충인 세력.' },
    { name:'BEAST', label:'FERAL FRONT', text:'육체성과 본능, 영역성을 전면에 내세우는 수인 세력. 전선의 충격파 역할을 맡는다.' }
  ],
  timeline: [
    'OLD WAR : 인간이 종족 전쟁에서 승리했다.',
    'CONTROL ERA : 자연종은 인간 질서 아래 편입되었다.',
    '2089 : 변이 개체와 해방군 기록이 동시다발적으로 출현했다.',
    'RUST ARK : 훼손된 생체 기록이 제한 등급으로 복원되었다.'
  ]
};

const CHARACTERS = [
  {
    id: 'seol-gongchan',
    displayName: 'Seol Gongchan 설공찬',
    enName: 'SEOL GONGCHAN',
    krName: '설공찬',
    type: 'HUMAN / COMMANDER',
    species: 'HUMAN',
    role: 'COMMANDER',
    creator: '@냠냠티비',
    accent: '#b8c2d3',
    affiliation: 'Human Resistance',
    danger: 'A+',
    status: 'ACTIVE',
    affirm: 'COMMAND VERIFIED',
    clearance: 'A-7 / HUMAN NODE',
    scan: 'TACTICAL SCAN COMPLETE',
    origin: 'HUMAN CONTROL ZONE',
    recordDate: '2089.09.21',
    archiveId: 'RA-H-01-GONGCHAN',
    mainImage: 'assets/images/seol_gongchan/seol_gongchan_01.jpg',
    gallery: galleryPaths('seol_gongchan', 3, 'jpg'),
    quote: '보호라는 말로 포장해도, 질서는 결국 누군가의 감시다.',
    metrics: { threat: 8, stability: 8, affinity: 2, control: 9 },
    profileBadges: ['AFFIRM : COMMAND VERIFIED', 'CLEARANCE : A-7 / HUMAN NODE', 'SCAN : TACTICAL COMPLETE'],
    identityFields: [
      ['ID', 'RA-H-01-GONGCHAN'], ['CLASS', 'HUMAN / COMMANDER'], ['CREATOR', '@냠냠티비'], ['FACTION', 'Human Resistance'], ['STATUS', 'ACTIVE'], ['AFFIRM', 'COMMAND VERIFIED'], ['CLEARANCE', 'A-7 / HUMAN NODE'], ['ORIGIN', 'HUMAN CONTROL ZONE'], ['RECORD DATE', '2089.09.21']
    ],
    summary: '무너진 세계에서도 질서를 다시 세우려는 인간 지휘관. 판단이 빠르고 통제력이 강하다.',
    profile: ['인간 대항군 총사령관.', '질서 재건을 명분으로 감시와 보호를 동시에 수행한다.', '협상 상대라면 유능하고 적이라면 번거롭다.'],
    story: '전쟁 이후의 혼란 속에서 인간 세력의 남은 규율을 수습한 지휘관. 그는 생존을 위해 필요한 폭력을 부정하지 않는다.',
    record: ['FIELD NOTE : 의사결정 속도 평균치 초과.', 'RISK : 조직 복구 능력 높음.']
  },
  {
    id: 'hwaryeon', 
    displayName: 'Hwaryeon 화련', 
    enName: 'HWARYEON', 
    krName: '화련', 
    type: 'PLANT / LOTUS', 
    species: 'PLANT', 
    role: 'LOTUS', 
    creator: '@냠냠티비', 
    accent: '#e68aa6', 
    affiliation: 'Plant Liberation Army', 
    danger: 'B+', 
    status: 'ACTIVE', 
    affirm: 'OBSERVED', 
    clearance: 'B-4 / BLOOM NODE', 
    scan: 'EMOTIONAL SCAN PARTIAL', 
    origin: 'WETLAND FRONT', 
    recordDate: '2089.09.18', 
    archiveId: 'RA-P-02-HWARYEON', 
    mainImage: 'assets/images/hwaryeon/hwaryeon_01.jpg', 
    gallery: galleryPaths('hwaryeon', 3, 'jpg'), 
    quote: '활짝 피었다는 건, 이미 물밑에서 다 끝났다는 뜻이야.', 
    metrics: { threat: 5, stability: 6, affinity: 7, control: 5 }, 
    profileBadges: ['AFFIRM : OBSERVED', 'CLEARANCE : B-4 / BLOOM NODE', 'SCAN : PARTIAL'], 
    identityFields: [['ID','RA-P-02-HWARYEON'],['CLASS','PLANT / LOTUS'],['CREATOR','@냠냠티비'],['FACTION','Plant Liberation Army'],['STATUS','ACTIVE'],['AFFIRM','OBSERVED'],['CLEARANCE','B-4 / BLOOM NODE'],
                     ['ORIGIN','WETLAND FRONT'],['RECORD DATE','2089.09.18']], 
    summary: '해맑고 장난스러운 연꽃 식목인. 무해한 얼굴로 잔혹한 전장을 통과한다.', 
    profile: ['연꽃 기반 식목인.', '밝은 태도와 전장의 잔혹함이 동시에 관측된다.', '정서 반응이 가볍지만 위험성이 낮다는 뜻은 아니다.'], 
    story: '그는 웃는 얼굴로 늪을 건넌다. 발밑에서 무엇이 썩고 있는지 알면서도 꽃은 피어난다.', 
    record: ['OBSERVATION : 친화적 접근 뒤 급격한 전술 전환.', 'CAUTION : 감정 표현과 위험도 불일치.']
  },
  {
    id: 'ordo', 
    displayName: 'Ordo 오르도', 
    enName: 'ORDO', 
    krName: '오르도', 
    type: 'INSECT / LOCUST', 
    species: 'INSECT', 
    role: 'LOCUST', 
    creator: '@냠냠티비', 
    accent: '#7f8f22', 
    affiliation: 'Swarm Domain', 
    danger: 'A', 
    status: 'UNSTABLE', 
    affirm: 'UNSTABLE CONFIRMED', 
    clearance: 'A-3 / SWARM ALERT', 
    scan: 'PATTERN BROKEN', 
    origin: 'DRY FIELD SECTOR', 
    recordDate: '2089.09.20', 
    archiveId: 'RA-I-03-ORDO', 
    mainImage: 'assets/images/ordo/ordo_01.jpg', 
    gallery: galleryPaths('ordo', 11, 'jpg'), 
    quote: '하나가 지나가면 흔적이 남고, 무리가 지나가면 세계가 바뀐다.', 
    metrics: { threat: 7, stability: 4, affinity: 2, control: 4 }, 
    profileBadges: ['AFFIRM : UNSTABLE CONFIRMED', 'CLEARANCE : A-3 / SWARM ALERT', 'SCAN : BROKEN'], 
    identityFields: [['ID','RA-I-03-ORDO'],['CLASS','INSECT / LOCUST'],['CREATOR','@냠냠티비'],['FACTION','Swarm Domain'],['STATUS','UNSTABLE'],['AFFIRM','UNSTABLE CONFIRMED'],['CLEARANCE','A-3 / SWARM ALERT'],['ORIGIN','DRY FIELD SECTOR'],['RECORD DATE','2089.09.20']], 
    summary: '메뚜기 충인. 집단 이동과 소모전을 상징하는 재난형 개체.', 
    profile: ['메뚜기 기반 충인.', '보급선과 경작지를 직접 위협한다.', '개체보다 군집 단위의 위험성이 높다.'], 
    story: '그가 지나간 자리에 남는 것은 전투의 잔해보다 기근에 가깝다.', 
    record: ['DAMAGE : 경작지 손실 다수.', 'PATTERN : 이동 방향 예측 어려움.']
  },
  {
    id: 'zephyr', 
    displayName: 'Zephyr 제피르', 
    enName: 'ZEPHYR', 
    krName: '제피르', 
    type: 'INSECT / DRAGONFLY', 
    species: 'INSECT', 
    role: 'DRAGONFLY', 
    creator: '@수백사', 
    accent: '#0084a8', 
    affiliation: 'Recon Wing', 
    danger: 'B+', 
    status: 'ACTIVE', 
    affirm: 'FIELD VERIFIED', 
    clearance: 'B-6 / RECON NODE', 
    scan: 'AERIAL SCAN COMPLETE', 
    origin: 'HIGH WIND ROUTE', 
    recordDate: '2089.09.19', 
    archiveId: 'RA-I-04-ZEPHYR', 
    mainImage: 'assets/images/zephyr/zephyr_01.png', 
    gallery: [imageItem('assets/images/zephyr/zephyr_01.png', 'IMAGE 01'), imageItem('assets/images/zephyr/zephyr_02.jpg', 'IMAGE 02'), imageItem('assets/images/zephyr/zephyr_03.png', 'IMAGE 03')], 
    quote: '"하늘은 거짓말을 하지 않아. 기록도 마찬가지고."', 
    metrics: { threat: 8.5, stability: 9.5, affinity: 6.5, control: 9 }, 
    profileBadges: ['AFFIRM : FIELD VERIFIED', 'CLEARANCE : B-6 / RECON NODE', 'SCAN : AERIAL COMPLETE'], 
    identityFields: [['ID','RA-I-04-ZEPHYR'],['CLASS','INSECT / DRAGONFLY'],['CREATOR','@수백사'],['FACTION','Recon Wing'],['STATUS','ACTIVE'],['AFFIRM','FIELD VERIFIED'],['CLEARANCE','B-6 / RECON NODE'],['ORIGIN','HIGH WIND ROUTE'],['RECORD DATE','2089.09.19']], 
    summary: ' 충인 진영 제1공중정찰대 제1관측반 반장, 제피르. 전장을 비행하며 지형과 적의 움직임을 기록하는 공중정찰기록관이다. 관찰을 멈추지 않으며, 필요한 순간에는 장거리 정밀사격으로 전황을 바꾼다.', 
    profile: ['192cm, 청록빛이 감도는 흑발, 청록+금빛 눈동자, 투명한 청록빛 왕잠자리 날개 네 장.', ' 침착한 관찰자, 능청스럽지만 신중한 현실주의자, 책임감이 강한 베테랑.', '항상 주변을 관찰하며 기록을 갱신한다. 높은 곳을 선호하고, 위험을 먼저 발견하며, 전투 후에도 현장을 재확인한다.', '공중 정찰·정보 분석·장거리 정밀사격에 특화된 충인 진영 공중정찰기록관.'], 
    story: '수많은 전장을 날며 누구보다 많은 죽음을 기록했다. 동료를 허위 보고와 무리한 작전으로 잃은 이후, 그는 기록에는 단 한 줄의 거짓도 남기지 않겠다고 맹세했다. 지금도 전장을 비행하며 세상의 변화를 기록하고, 살아남을 가치가 있는 진실을 찾는다.', 
    record: ['Sky Survey :  상공에서 넓은 시야를 확보해 지형, 적의 이동, 은폐물과 이상 현상을 실시간으로 분석한다. 발견한 정보는 즉시 기록·공유되며, 매복과 기습을 사전에 감지하는 데 특화되어 있다.', 'Dead Record : 관측을 마친 목표는 지정사수소총(DMR)으로 정밀 저격한다. 바람과 거리, 탄도를 계산해 단 한 발로 목표를 제압하는 제피르의 대표 전투 방식.']
  },
  {
    id: 'hale', 
    displayName: 'Hale 헤일', 
    enName: 'HALE', 
    krName: '헤일', 
    type: 'PLANT / HYDRANGEA', 
    species: 'PLANT', 
    role: 'HYDRANGEA', 
    creator: '@릴리브', 
    accent: '#9b8cff', 
    affiliation: 'Plant Liberation Army', 
    danger: 'A', 
    status: 'ACTIVE', 
    affirm: 'VERIFIED', 
    clearance: 'A-7 / STRATEGY NODE', 
    scan: 'BIO SIGNAL COMPLETE', 
    origin: 'HYDRANGEA FRONT', 
    recordDate: '2089.09.21', 
    archiveId: 'RA-P-05-HALE', 
    mainImage: 'assets/images/hale/hale_01.png', 
    gallery: [
      ...galleryPaths('hale', 2, 'png'),
      videoItem('assets/videos/hale/hale_01.mp4', 'assets/videos/hale/hale_01_poster.png', 'MOTION ARCHIVE 01')
    ], quote: '"좋은데요. 실패할 부분이 너무 잘 보여서."', 
    metrics: { threat: 8, stability: 6, affinity: 4, control: 10 }, 
    profileBadges: ['AFFIRM : VERIFIED', 'CLEARANCE : A-7 / STRATEGY NODE', 'SCAN : COMPLETE'], 
    identityFields: [['ID','RA-P-05-HALE'],['CLASS','PLANT / HYDRANGEA'],['CREATOR','@릴리브'],['FACTION','Plant Liberation Army'],['STATUS','ACTIVE'],['AFFIRM','VERIFIED'],['CLEARANCE','A-7 / STRATEGY NODE'],['ORIGIN','HYDRANGEA FRONT'],['RECORD DATE','2089.09.21']], 
    summary: '식물 해방군 소속 전략관. 전면전보다 정보전을 담당하며, 수국 군락을 이용한 감시망을 구축해 적대 세력의 동향을 분석한다. 불필요한 교전을 피하지만, 작전을 방해하는 적은 망설임 없이 제거한다.', 
    profile: ['외형 핵심: 마른 장신, 흐린 청회색 머리, 탁한 청보라색 눈, 잎맥 문양', '성격 핵심: 까칠함, 현실주의, 냉소적, 직설적', '행동 특징: 빈정거리는 농담, 효율과 구조 중시, 실무형 사고', '능력 또는 역할: 정보 분석, 감시망 구축, 교란 및 전술 지휘'], 
    story: '인간 통치 시절, 장식용 화초로 취급되며 무력하게 소비되었던 과거를 가졌다. 인간의 지배 질서가 얼마나 허술하고 오만한지에 대한 회의감을 바탕으로, 감정적인 복수 대신 체계적인 해체를 통한 완전한 해방을 추구한다. 그는 인간이 다시는 다른 종족을 지배할 수 없는 세계를 만드는 것을 궁극적인 목표로 삼고 있으며, 이를 위해 어떤 동맹도, 어떤 희생도 감수할 준비가 되어 있다.', 
    record: ['『Hydrangea Network』 : 도시 곳곳의 수국 군락과 신경망처럼 연결되어 정보를 공유한다. 이를 통해 인간 생존자의 이동 경로, 은신처, 보급로 등을 파악하고 전장의 흐름을 실시간으로 분석한다.', '『Toxic Pollen』 : 치명적인 독성을 지닌 꽃가루를 살포한다. 직접적인 살상보다는 적의 시야를 방해하고 환각과 호흡 교란을 유발하여 전술적 우위를 점하는 교란 능력에 가깝다.']
  },
  {
    id: 'arens', 
    displayName: 'Arens 아렌스', 
    enName: 'ARENS', 
    krName: '아렌스', 
    type: 'INSECT / ASSASSIN', 
    species: 'INSECT', 
    role: 'ASSASSIN', 
    creator: '@반엽', 
    accent: '#d37c1f', 
    affiliation: 'Covert Swarm', 
    danger: 'A+', 
    status: 'CLASSIFIED', 
    affirm: 'REDACTED', 
    clearance: 'BLACK / COVERT NODE', 
    scan: 'SIGNATURE MASKED', 
    origin: 'UNKNOWN', 
    recordDate: 'REDACTED', 
    archiveId: 'RA-I-06-ARENS',
    mainImage: 'assets/images/arens/arens_01.png', 
    gallery: galleryPaths('arens', 5, 'png'), 
    quote: '"비명은 짧게 부탁드립니다."', 
    metrics: { threat: 9, stability: 8, affinity: 1, control: 8 }, 
    profileBadges: ['AFFIRM : REDACTED', 'CLEARANCE : BLACK', 'SCAN : MASKED'], identityFields: [['ID','RA-I-06-ARENS'],['CLASS','INSECT / ASSASSIN'],['CREATOR','@반엽'],['FACTION','Covert Swarm'],['STATUS','CLASSIFIED'],['AFFIRM','REDACTED'],['CLEARANCE','BLACK / COVERT NODE'],['ORIGIN','UNKNOWN'],['RECORD DATE','REDACTED']], 
    summary: '암살자형 충인. 은신과 침투 기록이 대부분 삭제되어 있다.', 
    profile: ['외형 핵심: 흑발, 금안, 탄탄하고 민첩한 체형, 숨길 수 있는 거대한 나비 날개, 검은색 특수공작조 전투복', '성격 핵심: 차분하고 과묵함, 임무 최우선, 메마른 감정', '행동 특징: 말보다 행동이 앞섬, 목적을 위해 수단을 가리지 않음. 임무를 위해 기꺼이 스스로를 내던질 수 있다.', '능력 또는 역할: 은신, 잠입, 암살, 결박'], 
    story: '과거 인간의 "방역 작전"으로 실바나 독나비 군락 전체가 몰살당했을 때, 유일하게 살아남은 생존자. 여동생의 죽음을 눈앞에서 목격한 뒤 깊은 트라우마와 인간에 대한 강한 증오를 갖게 되었다. 현재는 충인 진영의 칼날이 되어, 자신에게서 모든 것을 앗아간 적들을 박멸하는 데 삶을 바치고 있다.', 
    record: ['『Shadow Camouflage』 : 주변 그림자에 스며들어 자신의 모습을 완벽하게 감춘다. 소리와 냄새까지 차단하여 적의 감각을 기만, 은밀한 침투 및 탈출에 사용되는 핵심 생존 기술이다.', '『Cocoon Thread & Venom Sting』 : 손끝에서 가늘고 강인한 나비고치의 실을 방출해 대상을 결박하거나 함정을 설치한다. 맹독침은 단일 대상을 즉시 무력화시키는 치명적인 공격 수단이다.']
  },
  {
    id: 'kael', 
    displayName: 'Kael 카엘', 
    enName: 'KAEL', 
    krName: '카엘', 
    type: 'BEAST / WOLF', 
    species: 'BEAST', 
    role: 'WOLF', 
    creator: '@떯기', 
    accent: '#6f8398', 
    affiliation: 'Feral Front', 
    danger: 'A', 
    status: 'ACTIVE', 
    affirm: 'CONFIRMED', 
    clearance: 'A-5 / PACK NODE', 
    scan: 'TRACKING COMPLETE', 
    origin: 'NORTHERN RUINS', 
    recordDate: '2089.09.17', 
    archiveId: 'RA-B-07-KAEL', 
    mainImage: 'assets/images/kael/kael_01.png', 
    gallery: [
      ...galleryPaths('kael', 6, 'png'),
      imageItem('assets/images/kael/kael_07.jpg', 'IMAGE 07'),
      imageItem('assets/images/kael/kael_08.png', 'IMAGE 08')
    ], quote: '"나의 송곳니와 발톱은 오직 부족을 위협하는 자에게만 향한다."', 
    metrics: { threat: 8, stability: 6, affinity: 4, control: 9 }, 
    profileBadges: ['AFFIRM : CONFIRMED', 'CLEARANCE : A-5 / PACK NODE', 'SCAN : TRACKING COMPLETE'], 
    identityFields: [['ID','RA-B-07-KAEL'],['CLASS','BEAST / WOLF'],['CREATOR','@떯기'],['FACTION','Feral Front'],['STATUS','ACTIVE'],['AFFIRM','CONFIRMED'],['CLEARANCE','A-5 / PACK NODE'],['ORIGIN','NORTHERN RUINS'],['RECORD DATE','2089.09.17']], 
    summary: '잿빛발톱 부족의 현 족장이자 무리의 최전선을 책임지는 지휘관. 인간형을 유지하며 전황을 통제하지만, 유사시에는 직접 신체를 강화해 적진을 돌파하는 근접 육탄전의 스페셜리스트이다. 그는 전술적 판단에 따라 최소한의 힘을 개방하며, 무리의 피해를 최소화하는 것을 최우선 목표로 삼는다.', 
    profile: ['외형 핵심: 긴 잿빛 장발, 투명한 벽안, 192cm의 장신, 회색 계열의 제복.', '성격 핵심: 진중하고 책임감이 강하며, 대의를 우선시하는 지도자. 겉은 차가워 보이나 속은 다정하다.', '행동 특징: 매사 신중하게 판단하며 행동. 감정을 잘 드러내지 않으나, 분노나 슬픔이 극에 달하면 미세하게 표정이나 목소리가 흔들린다.', '능력 또는 역할: 늑대 수인 족장, 근접 육탄전 특화, 부분적 신체 변형.'], 
    story: '10년 전, 족장으로 부임한 직후 겪은 대규모 전쟁에서 부족의 3분의 1을 잃었다. 이 사건은 그의 가장 큰 트라우마로 남아, 다시는 동족을 잃지 않겠다는 강한 책임감과 신념을 형성했다. 그는 대의와 무리의 생존을 위해서라면 인간과의 일시적 협약도 감수하며, 모든 결정을 개인의 감정보다 집단의 이익에 초점을 맞춰 내린다. 그의 진중함과 냉정함은 과거의 상실에서 비롯된, 무리를 지키기 위한 방어기제이다.', 
    record: ['『Primal Instinct』 : 달의 주기나 극심한 감정 변화에 반응하여 늑대의 본능이 깨어난다. 전투 시 청각, 후각 등 오감이 극도로 예민해져 적의 기척을 감지하고 움직임을 예측하는 데 사용된다. 평상시에는 억제되어 있으나, 통제력을 상실할 경우 이성을 잃고 야성에 지배당할 위험이 있다.', '『Partial Polymorph』 : 전투 상황이나 필요에 따라 신체 일부를 늑대의 형태로 변형 및 강화한다. 손톱을 날카로운 발톱으로 바꾸어 근접전을 펼치거나, 다리 근력을 강화하여 폭발적인 기동성을 확보하는 등 상황에 맞춰 유연하게 신체 능력을 운용한다. 완전한 늑대 형태로 변하는 것은 극히 드물며, 이는 모든 힘을 개방했음을 의미한다.']
  },
  {
    id: 'vulcan', 
    displayName: 'Vulcan 발칸', 
    enName: 'VULCAN', 
    krName: '발칸', 
    type: 'BEAST / BULLFIGHT', 
    species: 'BEAST', 
    role: 'BULLFIGHT', 
    creator: '@밍묭', 
    accent: '#c9361f', 
    affiliation: 'Feral Front', 
    danger: 'A+', 
    status: 'VOLATILE', 
    affirm: 'IMPACT VERIFIED', 
    clearance: 'A-9 / BREACH NODE',
    scan: 'KINETIC SCAN COMPLETE', 
    origin: 'FRONTLINE BREACH',
    recordDate: '2089.09.22', 
    archiveId: 'RA-B-08-VULCAN', 
    mainImage: 'assets/images/vulcan/vulcan_01.png', 
    gallery: galleryPaths('vulcan', 4, 'png'), 
    quote: '"네놈들의 피로, 이 땅의 모든 것을 다시 붉게 물들여주마."', 
    metrics: { threat: 9, stability: 2, affinity: 3, control: 1 }, 
    profileBadges: ['AFFIRM : IMPACT VERIFIED', 'CLEARANCE : A-9 / BREACH NODE', 'SCAN : KINETIC COMPLETE'], 
    identityFields: [['ID','RA-B-08-VULCAN'],['CLASS','BEAST / BULLFIGHT'],['CREATOR','@밍묭'],['FACTION','Feral Front'],['STATUS','VOLATILE'],['AFFIRM','IMPACT VERIFIED'],['CLEARANCE','A-9 / BREACH NODE'],['ORIGIN','FRONTLINE BREACH'],['RECORD DATE','2089.09.22']], 
    summary: '적각단(赤角團)의 수장. 인간 문명의 파괴와 수인 해방을 목표로 하는 무력 단체를 이끈다. 전장에서 모든 것을 맨몸으로 부수고 돌파하는 최선봉이자, 수하에게는 절대적인 보호를 제공하는 지배자다.', 
    profile: ['외형 핵심: 205cm의 거구, 전신을 뒤덮은 낙인과 흉터, 머리 위로 솟은 검고 날카로운 뿔, 짙은 붉은색 머리카락과 동색의 눈동자.', '성격 핵심: 본능과 욕망에 극단적으로 충실, 병적인 승부욕, 강자에 대한 집착과 약자에 대한 경멸적 보호 본능.', '행동 특징: 거침없고 직설적이며, 파괴를 망설이지 않음. 자신의 영역과 소유물에 대한 광적인 집착.', '능력 또는 역할: 적진을 돌파하는 돌격대장, 초인적인 근력과 내구력을 이용한 근접 파괴.'], 
    story: '인간들의 유흥을 위해 투우장에서 태어나고 길러진 투우소. 벗어날 수 없는 굴욕과 고통 속에서 인간을 향한 증오만을 키웠다. 세상이 무너지던 날, 자신을 억압하던 모든 것을 파괴하고 피의 복수를 시작했다. 그는 이제 부서진 세계의 폐허 위에서 오직 자신의 본능에 따라 움직이며, 인간이라는 종족의 완전한 절멸을 목표로 삼는다.', 
    record: ['『Crimson Charge』 : 목표를 향해 무자비하게 돌진하는 능력. 충돌 시 발생하는 충격파는 주변 지형을 파괴하며, 속도가 붙을수록 파괴력이 기하급수적으로 증가한다. 방어선을 붕괴시키거나 거대 구조물을 파괴하는 데 사용된다.', '『Tyrant\'s Roar』 : 분노를 담아 포효하여 주변 적들의 사기를 꺾고 일시적인 공포 상태에 빠뜨린다. 이 포효는 아군의 투지를 끌어올리는 효과도 지닌다. 전장의 흐름을 바꾸거나, 아군을 구출할 때 사용한다. ']
  },
  {
    id: 'harmel', 
    displayName: 'Harmel 하르멜', 
    enName: 'HARMEL', 
    krName: '하르멜', 
    type: 'INSECT / QUEEN BEE', 
    species: 'INSECT', 
    role: 'QUEEN BEE', 
    creator: '@햄솔이', 
    accent: '#d99a1e', 
    affiliation: 'Hornet Legion', 
    danger: 'S', 
    status: 'MUTATED', 
    affirm: 'MUTATION CONFIRMED', 
    clearance: 'S-1 / HIVE CROWN', 
    scan: 'TOXIN SCAN COMPLETE', 
    origin: 'NUCLEAR WASTE ZONE', 
    recordDate: '2089.09.23', 
    archiveId: 'RA-I-09-HARMEL', 
    mainImage: 'assets/images/harmel/harmel_01.png', 
    gallery: galleryPaths('harmel', 7, 'png'), 
    quote: '"나의 낙원에 온 걸 환영해. 여기서 너는… 가장 달콤한 꿈을 꾸게 될 거야."', 
    metrics: { threat: 9, stability: 4, affinity: 8, control: 10 }, 
    profileBadges: ['AFFIRM : MUTATION CONFIRMED', 'CLEARANCE : S-1 / HIVE CROWN', 'SCAN : TOXIN COMPLETE'], 
    identityFields: [['ID','RA-INSECT-MUTANT-QUEEN-031'],['CLASS','INSECT / QUEEN BEE'],['CREATOR','@햄솔이'],['FACTION','Hornet Legion'],['STATUS','MUTATED'],['AFFIRM','MUTATION CONFIRMED'],['CLEARANCE','S-1 / HIVE CROWN'],['ORIGIN','NUCLEAR WASTE ZONE'],['RECORD DATE','2089.09.23']], 
    summary: '말벌과 꿀벌의 특성을 모두 지닌 변이체 군주. 페로몬과 독침을 이용해 적을 무력화하고 아군을 통제하는 전장의 지배자이며, 군단 전체를 지휘하는 여왕으로서 기능한다. 그는 전술적으로 대상을 고립시킨 후, 심리적 지배와 정신적 속박을 통해 서서히 복속시킨다.', 
    profile: ['외형 핵심: 황금빛과 검은색이 섞인 긴 머리, 호박색 눈동자, 등 뒤의 날개 문양.','성격 핵심: 계산된 다정함, 이기적인 지배욕, 서늘한 권위.', '행동 특징: 상대의 체향을 맡거나 부드럽게 접촉하며 심리적 거리를 좁힌다.', '능력 또는 역할: 독과 페로몬을 이용한 정신 지배, 군단 통솔.'], 
    story: '인간에게 패배하고 억압받던 곤충 종족의 일원이었으나, 핵 폐기물 유출로 인해 여왕벌의 힘을 각성한 변이체. 그는 종족의 생존과 번영을 위해 다른 종족을 이용하고 희생시키는 것을 당연하게 여긴다. 현재 자신의 군단을 확장하고 후계를 생산할 대상을 물색하며, 궁극적으로는 인간에게 복수하고 세계의 지배권을 되찾는 것을 목표로 삼고 있다.', 
    record: ['『Queen\'s Venom』 : 혀끝에 숨겨진 미세 독침을 통해 신경계에 작용하는 독을 주입한다. 초기에는 강렬한 쾌감과 마비를 유발하며, 지속적으로 주입될 시 대상을 정신적으로 예속시켜 하르멜을 자신의 ‘여왕’으로 각인시키는 효과를 가진다. 키스나 신체 접촉을 통해 은밀하게 주입된다.', '『Apidae Dominion』 : 강력한 페로몬을 방출하여 주변의 벌들을 통솔하고, 대상의 감정과 행동에 영향을 미친다. 전투 시에는 날개를 펼쳐 적을 감싸고 움직임을 봉쇄하는 \'봉인교미\' 자세로 상대를 완전히 무력화시키며, 동시에 독을 주입하여 지배를 완성한다.']
  },
  {
    id: 'pavel', 
    displayName: 'Pavel 파벨', 
    enName: 'PAVEL', 
    krName: '파벨', 
    type: 'PLANT / OPIUM POPPY', 
    species: 'PLANT', 
    role: 'OPIUM POPPY', 
    creator: '@깅루나', 
    accent: '#9b174d', 
    affiliation: 'Plant Liberation Army', 
    danger: 'A', 
    status: 'ACTIVE', 
    affirm: 'CAUTION VERIFIED', 
    clearance: 'A-6 / SEDATION NODE', 
    scan: 'NARCOTIC SCAN COMPLETE', 
    origin: 'RED FIELD SECTOR', 
    recordDate: '2089.09.20', 
    archiveId: 'RA-P-10-PAVEL', 
    mainImage: 'assets/images/parvel/parvel_01.png', 
    gallery: galleryPaths('parvel', 11, 'png'), 
    quote: '"어디까지 버틸 수 있는지… 궁금해졌거든."', 
    metrics: { threat: 6, stability: 9, affinity: 3, control: 10 }, 
    profileBadges: ['AFFIRM : CAUTION VERIFIED', 'CLEARANCE : A-6 / SEDATION NODE', 'SCAN : NARCOTIC COMPLETE'], 
    identityFields: [['ID','RA-P-10-PAVEL'],['CLASS','PLANT / OPIUM POPPY'],['CREATOR','@깅루나'],['FACTION','Plant Liberation Army'],['STATUS','ACTIVE'],['AFFIRM','CAUTION VERIFIED'],['CLEARANCE','A-6 / SEDATION NODE'],['ORIGIN','RED FIELD SECTOR'],['RECORD DATE','2089.09.20']], 
    summary: '향기를 알아챘을 땐, 이미 그의 꽃밭 안이었다.', 
    profile: ['외형 핵심: 198cm, 붉은 장발과 적안, 창백한 피부 위로 번지는 검붉은 꽃맥','성격 핵심: 능글맞음, 계산적, 여유로움, 심리전의 대가', '행동 특징: 항상 미소를 유지하며 상대를 관찰하고, 대화의 주도권을 놓지 않음', '능력 또는 역할: 컨트롤러, 환각 조작, 영역 장악'], 
    story: '한때는 대지에 속박된 존재였으나, 종족 전쟁이 다시 시작되며 힘을 되찾았다. 인간의 복잡한 심리와 욕망에 깊은 흥미를 느껴, 그들을 관찰하고 시험하는 것을 즐긴다. 바엘과 함께 \'이 세계에 적합한 존재\'를 가려내는 것을 현재의 목표로 삼고 있으며, 단순한 생존을 넘어 어떤 선택을 내리는지를 기준으로 대상을 판단한다.', 
    record: ['『Crimson Delusion』 : 환각성 꽃가루를 이용한 전장 통제 및 심리전 특화.', '『PERSONALITY 』 : 높은 관찰력과 계산 능력 보유. 흥미를 느낀 대상은 즉시 제거하지 않고 장기간 관찰.']
  },
  {
    id: 'bael', 
    displayName: 'Bael 바엘', 
    enName: 'BAEL', 
    krName: '바엘', 
    type: 'BEAST / BLACK MAMBA', 
    species: 'BEAST', 
    role: 'BLACK MAMBA', 
    creator: '@깅루나', 
    accent: '#0f8f4f', 
    affiliation: 'Feral Front', 
    danger: 'S', 
    status: 'ACTIVE', 
    affirm: 'BLACKLISTED',
    clearance: 'S-2 / VENOM NODE',
    scan: 'NEUROTOXIN SCAN COMPLETE', 
    origin: 'SOUTHERN BLACK ZONE', 
    recordDate: '2089.09.24', 
    archiveId: 'RA-B-11-BAEL', 
    mainImage: 'assets/images/bael/bael_01.png', 
    gallery: galleryPaths('bael', 11, 'png'), 
    quote: '"살아남아봐. 끝까지.."', 
    metrics: { threat: 10, stability: 7, affinity: 2, control: 6 }, 
    profileBadges: ['AFFIRM : BLACKLISTED', 'CLEARANCE : S-2 / VENOM NODE', 'SCAN : NEUROTOXIN COMPLETE'], 
    identityFields: [['ID','RA-B-11-BAEL'],['CLASS','BEAST / BLACK MAMBA'],['CREATOR','@깅루나'],['FACTION','Feral Front'],['STATUS','ACTIVE'],['AFFIRM','BLACKLISTED'],['CLEARANCE','S-2 / VENOM NODE'],['ORIGIN','SOUTHERN BLACK ZONE'],['RECORD DATE','2089.09.24']], 
    summary: '그의 존재를 알아챘다면, 이미 그의 그림자 안이다.', 
    profile: ['외형 핵심: 202cm, 흑발과 흑안, 뱀을 연상시키는 세로 동공과 검은 송곳니', '성격 핵심: 과묵함, 냉정함, 현실적, 집요함', '행동 특징: 움직임을 최소화하며 상황을 관망, 위협으로 판단하면 즉시 행동', '능력 또는 역할: 피니셔, 맹독 공격, 암살'], 
    story: '인간들의 세계에서 살아남기 위해 포식자의 본능을 갈고닦았다. 그는 모든 종족을 잠재적 위협으로 간주하며, 불필요한 감정 소모 없이 가장 효율적인 방식으로 위협을 제거한다. 파벨의 전장 설계 능력을 신뢰하며 그와 함께 행동하지만, 이는 필요에 의한 공생일 뿐이다. 그의 유일한 신념은 \'생존\'이며, 이 세계에서 살아남을 가치가 있는 존재만이 남아야 한다고 믿는다.',
    record: ['『TACTIC』 : 고속 돌입 및 근접 섬멸 특화.', '『PERSONALITY』 : 침묵형 포식자. 위협 확인 즉시 제거.']
  }
];

const RELATIONS = [
  { from:'seol-gongchan', to:'hale', type:'WATCH', label:'전술 변수 감시', intensity:4, note:'수국 전략관의 판단력은 인정하지만 인간 질서의 통제 밖에 있는 핵심 변수로 분류한다.' },
  { from:'seol-gongchan', to:'hwaryeon', type:'WATCH', label:'해방군 핵심 관찰', intensity:3, note:'화련의 밝은 태도 뒤에 있는 전장 적응력을 위험 신호로 기록한다.' },
  { from:'seol-gongchan', to:'ordo', type:'HOSTILE', label:'보급로 파괴 위협', intensity:5, note:'메뚜기 군집형 개체를 인간 생존선과 식량 체계의 직접 위협으로 지정한다.' },
  { from:'hale', to:'zephyr', type:'ALLY', label:'정찰 협력', intensity:4, note:'제피르의 정찰 기록을 기반으로 헤일이 보급로 차단 계획을 세운다.' },
  { from:'hale', to:'seol-gongchan', type:'WATCH', label:'위험 감시', intensity:5, note:'인간 지휘관으로서 제거보다 장기 관찰 대상으로 분류한다.' },
  { from:'hwaryeon', to:'hale', type:'ALLY', label:'같은 전선', intensity:3, note:'방식은 다르지만 헤일의 전술 가치는 인정한다.' },
  { from:'arens', to:'hale', type:'WATCH', label:'침투 변수', intensity:3, note:'헤일의 전략망이 자신의 이동을 지나치게 정확히 읽는다고 판단한다.' },
  { from:'harmel', to:'ordo', type:'TRADE', label:'군집 거래', intensity:4, note:'하르멜은 오르도의 군집 이동을 전장 교란 자원으로 사용한다.' },
  { from:'bael', to:'kael', type:'WATCH', label:'포식자 견제', intensity:4, note:'서로의 영역성과 속도를 인정하지만 신뢰하지는 않는다.' },
  { from:'kael', to:'vulcan', type:'ALLY', label:'전선 돌파', intensity:4, note:'카엘은 발칸의 돌파력을 위험하지만 유용한 힘으로 본다.' },
  { from:'pavel', to:'hwaryeon', type:'PROTECT', label:'후방 진정', intensity:3, note:'파벨은 화련의 밝은 잔혹성이 전장에서 쉽게 소모될 수 있다고 본다.' },
  { from:'seol-gongchan', to:'bael', type:'HOSTILE', label:'고위험 제거 대상', intensity:5, note:'블랙맘바 수인 개체를 인간 방어선의 최우선 위협으로 분류한다.' },
  { from:'zephyr', to:'arens', type:'UNKNOWN', label:'식별 실패', intensity:2, note:'제피르의 관측 기록에도 아렌스의 이동 패턴은 부분적으로만 남는다.' }
];
